#######################################
# ACE GENERATED DELAYS SDC FILE
# Generated on: 2023.06.12 at 14:46:13 PDT
# By: ACE 9.0.1
# From project: vp_project
#######################################
# IO Ring Boundary Delays SDC File
#######################################
# SDC PVT Conditions:
# Voltage: 850 Temperature: n40 Corner: slow
#######################################
# Boundary pin delays for ethernet_0
# Clocks and Resets
set_clock_latency -source -late -rise 0.874598 [get_clocks ethernet_0_m0_ff_clk_divby2]
set_clock_latency -source -early -rise 0.787050 [get_clocks ethernet_0_m0_ff_clk_divby2]
set_clock_latency -source -late -rise 0.977481 [get_clocks ethernet_0_m1_ff_clk_divby2]
set_clock_latency -source -early -rise 0.882533 [get_clocks ethernet_0_m1_ff_clk_divby2]
set_clock_latency -source -late -rise 0.835176 [get_clocks ethernet_0_ref_clk_divby2]
set_clock_latency -source -early -rise 0.786575 [get_clocks ethernet_0_ref_clk_divby2]
# Quad MAC 0 Flow Control
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 2.446 [get_ports ethernet_0_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 2.5014 [get_ports ethernet_0_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.0461 [get_ports ethernet_0_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.1053 [get_ports ethernet_0_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 2.5093 [get_ports ethernet_0_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 2.5745 [get_ports ethernet_0_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.0817 [get_ports ethernet_0_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.141 [get_ports ethernet_0_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 2.4073 [get_ports ethernet_0_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 2.4593 [get_ports ethernet_0_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.0519 [get_ports ethernet_0_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.0975 [get_ports ethernet_0_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 2.3767 [get_ports ethernet_0_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 2.4296 [get_ports ethernet_0_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.1867 [get_ports ethernet_0_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.2366 [get_ports ethernet_0_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 2.417 [get_ports ethernet_0_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 2.4579 [get_ports ethernet_0_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.0796 [get_ports ethernet_0_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.1238 [get_ports ethernet_0_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 2.3185 [get_ports ethernet_0_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 2.3852 [get_ports ethernet_0_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.9583 [get_ports ethernet_0_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.0262 [get_ports ethernet_0_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 2.3371 [get_ports ethernet_0_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 2.3839 [get_ports ethernet_0_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.968 [get_ports ethernet_0_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.0299 [get_ports ethernet_0_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 2.3885 [get_ports ethernet_0_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 2.4363 [get_ports ethernet_0_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.184 [get_ports ethernet_0_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.2295 [get_ports ethernet_0_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.3258 [get_ports ethernet_0_quad0_emac_pause_on[8]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.3986 [get_ports ethernet_0_quad0_emac_pause_on[8]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.2708 [get_ports ethernet_0_quad0_emac_pause_on[9]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.3053 [get_ports ethernet_0_quad0_emac_pause_on[9]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.2201 [get_ports ethernet_0_quad0_emac_pause_on[10]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.2631 [get_ports ethernet_0_quad0_emac_pause_on[10]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.2111 [get_ports ethernet_0_quad0_emac_pause_on[11]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.2561 [get_ports ethernet_0_quad0_emac_pause_on[11]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.2272 [get_ports ethernet_0_quad0_emac_pause_on[12]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.2702 [get_ports ethernet_0_quad0_emac_pause_on[12]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.2415 [get_ports ethernet_0_quad0_emac_pause_on[13]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.2885 [get_ports ethernet_0_quad0_emac_pause_on[13]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.2618 [get_ports ethernet_0_quad0_emac_pause_on[14]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.3169 [get_ports ethernet_0_quad0_emac_pause_on[14]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.3634 [get_ports ethernet_0_quad0_emac_pause_on[15]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.4336 [get_ports ethernet_0_quad0_emac_pause_on[15]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.3536 [get_ports ethernet_0_quad0_emac_pause_on[16]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.3685 [get_ports ethernet_0_quad0_emac_pause_on[16]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.3437 [get_ports ethernet_0_quad0_emac_pause_on[17]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.3571 [get_ports ethernet_0_quad0_emac_pause_on[17]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.3935 [get_ports ethernet_0_quad0_emac_pause_on[18]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.4365 [get_ports ethernet_0_quad0_emac_pause_on[18]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.4603 [get_ports ethernet_0_quad0_emac_pause_on[19]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.4889 [get_ports ethernet_0_quad0_emac_pause_on[19]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.36 [get_ports ethernet_0_quad0_emac_pause_on[20]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.4005 [get_ports ethernet_0_quad0_emac_pause_on[20]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.4855 [get_ports ethernet_0_quad0_emac_pause_on[21]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.5395 [get_ports ethernet_0_quad0_emac_pause_on[21]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.2935 [get_ports ethernet_0_quad0_emac_pause_on[22]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.3246 [get_ports ethernet_0_quad0_emac_pause_on[22]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.3996 [get_ports ethernet_0_quad0_emac_pause_on[23]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.4194 [get_ports ethernet_0_quad0_emac_pause_on[23]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.3406 [get_ports ethernet_0_quad0_emac_pause_on[24]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.3629 [get_ports ethernet_0_quad0_emac_pause_on[24]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.4049 [get_ports ethernet_0_quad0_emac_pause_on[25]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.426 [get_ports ethernet_0_quad0_emac_pause_on[25]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.3756 [get_ports ethernet_0_quad0_emac_pause_on[26]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.4035 [get_ports ethernet_0_quad0_emac_pause_on[26]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.3631 [get_ports ethernet_0_quad0_emac_pause_on[27]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.3771 [get_ports ethernet_0_quad0_emac_pause_on[27]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.3746 [get_ports ethernet_0_quad0_emac_pause_on[28]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.4326 [get_ports ethernet_0_quad0_emac_pause_on[28]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.3984 [get_ports ethernet_0_quad0_emac_pause_on[29]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.4496 [get_ports ethernet_0_quad0_emac_pause_on[29]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.354 [get_ports ethernet_0_quad0_emac_pause_on[30]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.3984 [get_ports ethernet_0_quad0_emac_pause_on[30]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.3585 [get_ports ethernet_0_quad0_emac_pause_on[31]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.3884 [get_ports ethernet_0_quad0_emac_pause_on[31]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.5937 [get_ports ethernet_0_quad0_emac_xoff_gen[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.6176 [get_ports ethernet_0_quad0_emac_xoff_gen[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.5437 [get_ports ethernet_0_quad0_emac_xoff_gen[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.5872 [get_ports ethernet_0_quad0_emac_xoff_gen[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.5864 [get_ports ethernet_0_quad0_emac_xoff_gen[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.6155 [get_ports ethernet_0_quad0_emac_xoff_gen[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.5527 [get_ports ethernet_0_quad0_emac_xoff_gen[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.578 [get_ports ethernet_0_quad0_emac_xoff_gen[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.5801 [get_ports ethernet_0_quad0_emac_xoff_gen[4]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.6055 [get_ports ethernet_0_quad0_emac_xoff_gen[4]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.6739 [get_ports ethernet_0_quad0_emac_xoff_gen[5]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.7011 [get_ports ethernet_0_quad0_emac_xoff_gen[5]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.5466 [get_ports ethernet_0_quad0_emac_xoff_gen[6]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.5751 [get_ports ethernet_0_quad0_emac_xoff_gen[6]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.4801 [get_ports ethernet_0_quad0_emac_xoff_gen[7]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.5285 [get_ports ethernet_0_quad0_emac_xoff_gen[7]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2192 [get_ports ethernet_0_quad0_emac_xoff_gen[8]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2378 [get_ports ethernet_0_quad0_emac_xoff_gen[8]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2036 [get_ports ethernet_0_quad0_emac_xoff_gen[9]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2295 [get_ports ethernet_0_quad0_emac_xoff_gen[9]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.22 [get_ports ethernet_0_quad0_emac_xoff_gen[10]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.235 [get_ports ethernet_0_quad0_emac_xoff_gen[10]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2214 [get_ports ethernet_0_quad0_emac_xoff_gen[11]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2486 [get_ports ethernet_0_quad0_emac_xoff_gen[11]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2259 [get_ports ethernet_0_quad0_emac_xoff_gen[12]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2592 [get_ports ethernet_0_quad0_emac_xoff_gen[12]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2407 [get_ports ethernet_0_quad0_emac_xoff_gen[13]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.271 [get_ports ethernet_0_quad0_emac_xoff_gen[13]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2303 [get_ports ethernet_0_quad0_emac_xoff_gen[14]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2506 [get_ports ethernet_0_quad0_emac_xoff_gen[14]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.1936 [get_ports ethernet_0_quad0_emac_xoff_gen[15]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2148 [get_ports ethernet_0_quad0_emac_xoff_gen[15]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2418 [get_ports ethernet_0_quad0_emac_xoff_gen[16]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2711 [get_ports ethernet_0_quad0_emac_xoff_gen[16]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.3241 [get_ports ethernet_0_quad0_emac_xoff_gen[17]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.3539 [get_ports ethernet_0_quad0_emac_xoff_gen[17]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.3135 [get_ports ethernet_0_quad0_emac_xoff_gen[18]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.3398 [get_ports ethernet_0_quad0_emac_xoff_gen[18]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.3919 [get_ports ethernet_0_quad0_emac_xoff_gen[19]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.421 [get_ports ethernet_0_quad0_emac_xoff_gen[19]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2525 [get_ports ethernet_0_quad0_emac_xoff_gen[20]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2824 [get_ports ethernet_0_quad0_emac_xoff_gen[20]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.3167 [get_ports ethernet_0_quad0_emac_xoff_gen[21]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.3335 [get_ports ethernet_0_quad0_emac_xoff_gen[21]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2678 [get_ports ethernet_0_quad0_emac_xoff_gen[22]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2916 [get_ports ethernet_0_quad0_emac_xoff_gen[22]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2567 [get_ports ethernet_0_quad0_emac_xoff_gen[23]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2848 [get_ports ethernet_0_quad0_emac_xoff_gen[23]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.3318 [get_ports ethernet_0_quad0_emac_xoff_gen[24]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.3496 [get_ports ethernet_0_quad0_emac_xoff_gen[24]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2535 [get_ports ethernet_0_quad0_emac_xoff_gen[25]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2704 [get_ports ethernet_0_quad0_emac_xoff_gen[25]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2309 [get_ports ethernet_0_quad0_emac_xoff_gen[26]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2533 [get_ports ethernet_0_quad0_emac_xoff_gen[26]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2535 [get_ports ethernet_0_quad0_emac_xoff_gen[27]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.27 [get_ports ethernet_0_quad0_emac_xoff_gen[27]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2724 [get_ports ethernet_0_quad0_emac_xoff_gen[28]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2929 [get_ports ethernet_0_quad0_emac_xoff_gen[28]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.322 [get_ports ethernet_0_quad0_emac_xoff_gen[29]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.3457 [get_ports ethernet_0_quad0_emac_xoff_gen[29]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2708 [get_ports ethernet_0_quad0_emac_xoff_gen[30]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2889 [get_ports ethernet_0_quad0_emac_xoff_gen[30]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2404 [get_ports ethernet_0_quad0_emac_xoff_gen[31]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.257 [get_ports ethernet_0_quad0_emac_xoff_gen[31]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.4187 [get_ports ethernet_0_quad0_lpi_txhold[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.4392 [get_ports ethernet_0_quad0_lpi_txhold[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2551 [get_ports ethernet_0_quad0_lpi_txhold[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2779 [get_ports ethernet_0_quad0_lpi_txhold[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.3263 [get_ports ethernet_0_quad0_lpi_txhold[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.3579 [get_ports ethernet_0_quad0_lpi_txhold[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2371 [get_ports ethernet_0_quad0_lpi_txhold[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2629 [get_ports ethernet_0_quad0_lpi_txhold[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay -0.8677 [get_ports ethernet_0_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay -0.8561 [get_ports ethernet_0_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay -1.0031 [get_ports ethernet_0_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay -0.9792 [get_ports ethernet_0_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay -0.9952 [get_ports ethernet_0_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay -0.9738 [get_ports ethernet_0_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay -0.9624 [get_ports ethernet_0_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay -0.9289 [get_ports ethernet_0_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay -0.9591 [get_ports ethernet_0_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay -0.9631 [get_ports ethernet_0_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay -1.0388 [get_ports ethernet_0_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay -1.0336 [get_ports ethernet_0_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay -1.0396 [get_ports ethernet_0_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay -1.035 [get_ports ethernet_0_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay -1.043 [get_ports ethernet_0_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay -1.0269 [get_ports ethernet_0_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.4 [get_ports ethernet_0_quad0_tx_hold_req[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.3888 [get_ports ethernet_0_quad0_tx_hold_req[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.1746 [get_ports ethernet_0_quad0_tx_hold_req[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.1946 [get_ports ethernet_0_quad0_tx_hold_req[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.298 [get_ports ethernet_0_quad0_tx_hold_req[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.3145 [get_ports ethernet_0_quad0_tx_hold_req[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2391 [get_ports ethernet_0_quad0_tx_hold_req[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2602 [get_ports ethernet_0_quad0_tx_hold_req[3]]
# Quad MAC 0 Status
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.1897 [get_ports ethernet_0_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.2484 [get_ports ethernet_0_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.3048 [get_ports ethernet_0_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.3261 [get_ports ethernet_0_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.2582 [get_ports ethernet_0_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.2675 [get_ports ethernet_0_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.2728 [get_ports ethernet_0_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.2847 [get_ports ethernet_0_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 2.1141 [get_ports ethernet_0_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 2.1716 [get_ports ethernet_0_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 2.223 [get_ports ethernet_0_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 2.2445 [get_ports ethernet_0_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 2.1787 [get_ports ethernet_0_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 2.1898 [get_ports ethernet_0_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 2.1896 [get_ports ethernet_0_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 2.2043 [get_ports ethernet_0_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.1552 [get_ports ethernet_0_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.191 [get_ports ethernet_0_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.1916 [get_ports ethernet_0_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.2079 [get_ports ethernet_0_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.1617 [get_ports ethernet_0_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.2045 [get_ports ethernet_0_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.2251 [get_ports ethernet_0_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.2405 [get_ports ethernet_0_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 2.0828 [get_ports ethernet_0_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 2.119 [get_ports ethernet_0_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 2.1045 [get_ports ethernet_0_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 2.1225 [get_ports ethernet_0_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 2.0956 [get_ports ethernet_0_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 2.1359 [get_ports ethernet_0_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 2.155 [get_ports ethernet_0_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 2.1702 [get_ports ethernet_0_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 2.1345 [get_ports ethernet_0_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 2.1313 [get_ports ethernet_0_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 2.1173 [get_ports ethernet_0_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 2.1574 [get_ports ethernet_0_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 2.2348 [get_ports ethernet_0_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 2.2252 [get_ports ethernet_0_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 2.0428 [get_ports ethernet_0_m0_mac_tx_underflow[3]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 2.069 [get_ports ethernet_0_m0_mac_tx_underflow[3]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay 2.0892 [get_ports ethernet_0_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay 2.0892 [get_ports ethernet_0_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay 2.0509 [get_ports ethernet_0_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay 2.0874 [get_ports ethernet_0_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay 2.1777 [get_ports ethernet_0_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay 2.1713 [get_ports ethernet_0_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay 1.9912 [get_ports ethernet_0_m0_mac_tx_underflow[3]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay 2.0174 [get_ports ethernet_0_m0_mac_tx_underflow[3]]
# Boundary pin delays for ethernet_1
# Clocks and Resets
set_clock_latency -source -late -rise 0.884624 [get_clocks ethernet_1_m0_ff_clk_divby2]
set_clock_latency -source -early -rise 0.776704 [get_clocks ethernet_1_m0_ff_clk_divby2]
set_clock_latency -source -late -rise 0.971567 [get_clocks ethernet_1_m1_ff_clk_divby2]
set_clock_latency -source -early -rise 0.871954 [get_clocks ethernet_1_m1_ff_clk_divby2]
set_clock_latency -source -late -rise 0.807699 [get_clocks ethernet_1_ref_clk_divby2]
set_clock_latency -source -early -rise 0.766121 [get_clocks ethernet_1_ref_clk_divby2]
# Quad MAC 0 Flow Control
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 2.3909 [get_ports ethernet_1_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 2.4327 [get_ports ethernet_1_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.991 [get_ports ethernet_1_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.0366 [get_ports ethernet_1_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 2.3524 [get_ports ethernet_1_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 2.3762 [get_ports ethernet_1_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.9248 [get_ports ethernet_1_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.9426 [get_ports ethernet_1_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 2.3497 [get_ports ethernet_1_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 2.3862 [get_ports ethernet_1_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.9943 [get_ports ethernet_1_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.0243 [get_ports ethernet_1_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 2.3157 [get_ports ethernet_1_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 2.3527 [get_ports ethernet_1_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 2.1257 [get_ports ethernet_1_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.1598 [get_ports ethernet_1_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 2.3653 [get_ports ethernet_1_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 2.3906 [get_ports ethernet_1_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 2.0279 [get_ports ethernet_1_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.0565 [get_ports ethernet_1_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 2.3063 [get_ports ethernet_1_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 2.369 [get_ports ethernet_1_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.9461 [get_ports ethernet_1_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.01 [get_ports ethernet_1_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 2.3112 [get_ports ethernet_1_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 2.3497 [get_ports ethernet_1_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.9421 [get_ports ethernet_1_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.9957 [get_ports ethernet_1_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 2.3386 [get_ports ethernet_1_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 2.3745 [get_ports ethernet_1_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 2.1342 [get_ports ethernet_1_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.1678 [get_ports ethernet_1_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.1971 [get_ports ethernet_1_quad0_emac_pause_on[8]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.231 [get_ports ethernet_1_quad0_emac_pause_on[8]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.2311 [get_ports ethernet_1_quad0_emac_pause_on[9]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.2539 [get_ports ethernet_1_quad0_emac_pause_on[9]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.1886 [get_ports ethernet_1_quad0_emac_pause_on[10]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.2213 [get_ports ethernet_1_quad0_emac_pause_on[10]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.1724 [get_ports ethernet_1_quad0_emac_pause_on[11]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.2051 [get_ports ethernet_1_quad0_emac_pause_on[11]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.1874 [get_ports ethernet_1_quad0_emac_pause_on[12]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.2198 [get_ports ethernet_1_quad0_emac_pause_on[12]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.1864 [get_ports ethernet_1_quad0_emac_pause_on[13]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.2196 [get_ports ethernet_1_quad0_emac_pause_on[13]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.2124 [get_ports ethernet_1_quad0_emac_pause_on[14]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.2547 [get_ports ethernet_1_quad0_emac_pause_on[14]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.2319 [get_ports ethernet_1_quad0_emac_pause_on[15]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.2604 [get_ports ethernet_1_quad0_emac_pause_on[15]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.3094 [get_ports ethernet_1_quad0_emac_pause_on[16]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3118 [get_ports ethernet_1_quad0_emac_pause_on[16]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.3066 [get_ports ethernet_1_quad0_emac_pause_on[17]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3082 [get_ports ethernet_1_quad0_emac_pause_on[17]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.2972 [get_ports ethernet_1_quad0_emac_pause_on[18]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3117 [get_ports ethernet_1_quad0_emac_pause_on[18]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.4247 [get_ports ethernet_1_quad0_emac_pause_on[19]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.4409 [get_ports ethernet_1_quad0_emac_pause_on[19]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.2911 [get_ports ethernet_1_quad0_emac_pause_on[20]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3137 [get_ports ethernet_1_quad0_emac_pause_on[20]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.4187 [get_ports ethernet_1_quad0_emac_pause_on[21]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.454 [get_ports ethernet_1_quad0_emac_pause_on[21]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.2642 [get_ports ethernet_1_quad0_emac_pause_on[22]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.286 [get_ports ethernet_1_quad0_emac_pause_on[22]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.3406 [get_ports ethernet_1_quad0_emac_pause_on[23]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3345 [get_ports ethernet_1_quad0_emac_pause_on[23]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.3331 [get_ports ethernet_1_quad0_emac_pause_on[24]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3518 [get_ports ethernet_1_quad0_emac_pause_on[24]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.3387 [get_ports ethernet_1_quad0_emac_pause_on[25]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3409 [get_ports ethernet_1_quad0_emac_pause_on[25]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.3093 [get_ports ethernet_1_quad0_emac_pause_on[26]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3172 [get_ports ethernet_1_quad0_emac_pause_on[26]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.3247 [get_ports ethernet_1_quad0_emac_pause_on[27]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3282 [get_ports ethernet_1_quad0_emac_pause_on[27]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.32 [get_ports ethernet_1_quad0_emac_pause_on[28]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3608 [get_ports ethernet_1_quad0_emac_pause_on[28]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.3616 [get_ports ethernet_1_quad0_emac_pause_on[29]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.4007 [get_ports ethernet_1_quad0_emac_pause_on[29]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.3462 [get_ports ethernet_1_quad0_emac_pause_on[30]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3869 [get_ports ethernet_1_quad0_emac_pause_on[30]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.3061 [get_ports ethernet_1_quad0_emac_pause_on[31]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3192 [get_ports ethernet_1_quad0_emac_pause_on[31]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.576 [get_ports ethernet_1_quad0_emac_xoff_gen[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.5997 [get_ports ethernet_1_quad0_emac_xoff_gen[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.5152 [get_ports ethernet_1_quad0_emac_xoff_gen[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.5585 [get_ports ethernet_1_quad0_emac_xoff_gen[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.565 [get_ports ethernet_1_quad0_emac_xoff_gen[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.5941 [get_ports ethernet_1_quad0_emac_xoff_gen[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.5453 [get_ports ethernet_1_quad0_emac_xoff_gen[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.5701 [get_ports ethernet_1_quad0_emac_xoff_gen[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.5678 [get_ports ethernet_1_quad0_emac_xoff_gen[4]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.5932 [get_ports ethernet_1_quad0_emac_xoff_gen[4]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.5874 [get_ports ethernet_1_quad0_emac_xoff_gen[5]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.6135 [get_ports ethernet_1_quad0_emac_xoff_gen[5]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.5298 [get_ports ethernet_1_quad0_emac_xoff_gen[6]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.5584 [get_ports ethernet_1_quad0_emac_xoff_gen[6]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.469 [get_ports ethernet_1_quad0_emac_xoff_gen[7]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.5162 [get_ports ethernet_1_quad0_emac_xoff_gen[7]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2017 [get_ports ethernet_1_quad0_emac_xoff_gen[8]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2205 [get_ports ethernet_1_quad0_emac_xoff_gen[8]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1939 [get_ports ethernet_1_quad0_emac_xoff_gen[9]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2192 [get_ports ethernet_1_quad0_emac_xoff_gen[9]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2032 [get_ports ethernet_1_quad0_emac_xoff_gen[10]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2184 [get_ports ethernet_1_quad0_emac_xoff_gen[10]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2097 [get_ports ethernet_1_quad0_emac_xoff_gen[11]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2365 [get_ports ethernet_1_quad0_emac_xoff_gen[11]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1744 [get_ports ethernet_1_quad0_emac_xoff_gen[12]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.207 [get_ports ethernet_1_quad0_emac_xoff_gen[12]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2223 [get_ports ethernet_1_quad0_emac_xoff_gen[13]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.252 [get_ports ethernet_1_quad0_emac_xoff_gen[13]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2133 [get_ports ethernet_1_quad0_emac_xoff_gen[14]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2341 [get_ports ethernet_1_quad0_emac_xoff_gen[14]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1732 [get_ports ethernet_1_quad0_emac_xoff_gen[15]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.1941 [get_ports ethernet_1_quad0_emac_xoff_gen[15]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2317 [get_ports ethernet_1_quad0_emac_xoff_gen[16]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2608 [get_ports ethernet_1_quad0_emac_xoff_gen[16]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2719 [get_ports ethernet_1_quad0_emac_xoff_gen[17]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.301 [get_ports ethernet_1_quad0_emac_xoff_gen[17]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2473 [get_ports ethernet_1_quad0_emac_xoff_gen[18]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2737 [get_ports ethernet_1_quad0_emac_xoff_gen[18]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2541 [get_ports ethernet_1_quad0_emac_xoff_gen[19]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2806 [get_ports ethernet_1_quad0_emac_xoff_gen[19]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2441 [get_ports ethernet_1_quad0_emac_xoff_gen[20]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2733 [get_ports ethernet_1_quad0_emac_xoff_gen[20]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2374 [get_ports ethernet_1_quad0_emac_xoff_gen[21]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2525 [get_ports ethernet_1_quad0_emac_xoff_gen[21]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2465 [get_ports ethernet_1_quad0_emac_xoff_gen[22]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2702 [get_ports ethernet_1_quad0_emac_xoff_gen[22]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2275 [get_ports ethernet_1_quad0_emac_xoff_gen[23]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2551 [get_ports ethernet_1_quad0_emac_xoff_gen[23]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2745 [get_ports ethernet_1_quad0_emac_xoff_gen[24]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2912 [get_ports ethernet_1_quad0_emac_xoff_gen[24]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2242 [get_ports ethernet_1_quad0_emac_xoff_gen[25]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.241 [get_ports ethernet_1_quad0_emac_xoff_gen[25]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2084 [get_ports ethernet_1_quad0_emac_xoff_gen[26]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2302 [get_ports ethernet_1_quad0_emac_xoff_gen[26]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2388 [get_ports ethernet_1_quad0_emac_xoff_gen[27]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2553 [get_ports ethernet_1_quad0_emac_xoff_gen[27]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2311 [get_ports ethernet_1_quad0_emac_xoff_gen[28]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2508 [get_ports ethernet_1_quad0_emac_xoff_gen[28]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2694 [get_ports ethernet_1_quad0_emac_xoff_gen[29]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2929 [get_ports ethernet_1_quad0_emac_xoff_gen[29]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2563 [get_ports ethernet_1_quad0_emac_xoff_gen[30]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2741 [get_ports ethernet_1_quad0_emac_xoff_gen[30]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2311 [get_ports ethernet_1_quad0_emac_xoff_gen[31]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.247 [get_ports ethernet_1_quad0_emac_xoff_gen[31]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.4081 [get_ports ethernet_1_quad0_lpi_txhold[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.4285 [get_ports ethernet_1_quad0_lpi_txhold[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1953 [get_ports ethernet_1_quad0_lpi_txhold[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2166 [get_ports ethernet_1_quad0_lpi_txhold[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2822 [get_ports ethernet_1_quad0_lpi_txhold[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.3129 [get_ports ethernet_1_quad0_lpi_txhold[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1866 [get_ports ethernet_1_quad0_lpi_txhold[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.212 [get_ports ethernet_1_quad0_lpi_txhold[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay -0.9694 [get_ports ethernet_1_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay -0.9594 [get_ports ethernet_1_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay -1.0248 [get_ports ethernet_1_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay -1.0008 [get_ports ethernet_1_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay -1.0582 [get_ports ethernet_1_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay -1.0379 [get_ports ethernet_1_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay -1.0252 [get_ports ethernet_1_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay -0.9922 [get_ports ethernet_1_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay -1.0142 [get_ports ethernet_1_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay -1.0206 [get_ports ethernet_1_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay -1.0549 [get_ports ethernet_1_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay -1.05 [get_ports ethernet_1_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay -1.0835 [get_ports ethernet_1_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay -1.0805 [get_ports ethernet_1_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay -1.0752 [get_ports ethernet_1_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay -1.0603 [get_ports ethernet_1_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.3404 [get_ports ethernet_1_quad0_tx_hold_req[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.3294 [get_ports ethernet_1_quad0_tx_hold_req[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1616 [get_ports ethernet_1_quad0_tx_hold_req[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.1816 [get_ports ethernet_1_quad0_tx_hold_req[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2705 [get_ports ethernet_1_quad0_tx_hold_req[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2865 [get_ports ethernet_1_quad0_tx_hold_req[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2056 [get_ports ethernet_1_quad0_tx_hold_req[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2265 [get_ports ethernet_1_quad0_tx_hold_req[3]]
# Quad MAC 0 Status
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 2.1656 [get_ports ethernet_1_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.2163 [get_ports ethernet_1_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 2.2642 [get_ports ethernet_1_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.2731 [get_ports ethernet_1_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 2.233 [get_ports ethernet_1_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.234 [get_ports ethernet_1_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 2.246 [get_ports ethernet_1_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.2486 [get_ports ethernet_1_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 2.0933 [get_ports ethernet_1_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 2.143 [get_ports ethernet_1_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 2.1973 [get_ports ethernet_1_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 2.2058 [get_ports ethernet_1_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 2.1569 [get_ports ethernet_1_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 2.1601 [get_ports ethernet_1_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 2.1669 [get_ports ethernet_1_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 2.1726 [get_ports ethernet_1_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 2.1443 [get_ports ethernet_1_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.1768 [get_ports ethernet_1_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 2.1452 [get_ports ethernet_1_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.1482 [get_ports ethernet_1_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 2.152 [get_ports ethernet_1_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.1917 [get_ports ethernet_1_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 2.1994 [get_ports ethernet_1_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.206 [get_ports ethernet_1_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 2.0744 [get_ports ethernet_1_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 2.1075 [get_ports ethernet_1_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 2.08 [get_ports ethernet_1_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 2.0841 [get_ports ethernet_1_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 2.0884 [get_ports ethernet_1_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 2.1258 [get_ports ethernet_1_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 2.1318 [get_ports ethernet_1_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 2.1386 [get_ports ethernet_1_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 2.0999 [get_ports ethernet_1_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 2.0835 [get_ports ethernet_1_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 2.0775 [get_ports ethernet_1_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 2.104 [get_ports ethernet_1_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 2.2184 [get_ports ethernet_1_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 2.2048 [get_ports ethernet_1_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 2.0316 [get_ports ethernet_1_m0_mac_tx_underflow[3]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 2.0541 [get_ports ethernet_1_m0_mac_tx_underflow[3]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay 2.0556 [get_ports ethernet_1_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay 2.0431 [get_ports ethernet_1_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay 2.0261 [get_ports ethernet_1_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay 2.0499 [get_ports ethernet_1_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay 2.1689 [get_ports ethernet_1_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay 2.158 [get_ports ethernet_1_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay 1.9803 [get_ports ethernet_1_m0_mac_tx_underflow[3]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay 2.0027 [get_ports ethernet_1_m0_mac_tx_underflow[3]]
# Boundary pin delays for noc
# Boundary pin delays for pll_ddr
# Boundary pin delays for pll_eth_sys_ne_0
# Boundary pin delays for pll_eth_usr_ne_3
# Boundary pin delays for pll_gddr_SE
# Boundary pin delays for pll_gddr_SW
# Boundary pin delays for pll_noc_ne_1
# Boundary pin delays for pll_pcie
# Boundary pin delays for vp_clkio_ne
# Boundary pin delays for vp_clkio_nw
# Boundary pin delays for vp_clkio_se
# Boundary pin delays for vp_clkio_sw
# Boundary pin delays for vp_gpio_n_b0
# Core Data
# Boundary pin delays for vp_gpio_n_b1
# Core Data
# Boundary pin delays for vp_gpio_n_b2
# Core Data
# Boundary pin delays for vp_gpio_s_b0
# Core Data
# Boundary pin delays for vp_gpio_s_b1
# Core Clock
set_clock_latency -source -late -rise 0.733446 [get_clocks mcio_vio_45_10_clk]
set_clock_latency -source -early -rise 0.659128 [get_clocks mcio_vio_45_10_clk]
# Core Data
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay 2.1521 [get_ports mcio_vio_in[0]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay 2.1314 [get_ports mcio_vio_in[0]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay 1.8477 [get_ports mcio_vio_in[0]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay 1.8538 [get_ports mcio_vio_in[0]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay 2.062 [get_ports mcio_vio_in[1]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay 2.0659 [get_ports mcio_vio_in[1]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay 1.8697 [get_ports mcio_vio_in[1]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay 1.8807 [get_ports mcio_vio_in[1]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay 2.0648 [get_ports mcio_vio_in[2]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay 2.0593 [get_ports mcio_vio_in[2]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay 1.8602 [get_ports mcio_vio_in[2]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay 1.865 [get_ports mcio_vio_in[2]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay 2.1832 [get_ports mcio_vio_in[3]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay 2.1618 [get_ports mcio_vio_in[3]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay 1.8575 [get_ports mcio_vio_in[3]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay 1.8668 [get_ports mcio_vio_in[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7181 [get_ports mcio_dir[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.7011 [get_ports mcio_dir[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.787 [get_ports mcio_dir[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7829 [get_ports mcio_dir[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7358 [get_ports mcio_dir[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.6936 [get_ports mcio_dir[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.8065 [get_ports mcio_dir[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7824 [get_ports mcio_dir[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7457 [get_ports mcio_dir[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.6985 [get_ports mcio_dir[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.8085 [get_ports mcio_dir[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7792 [get_ports mcio_dir[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7406 [get_ports mcio_dir[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.6972 [get_ports mcio_dir[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.8013 [get_ports mcio_dir[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7753 [get_ports mcio_dir[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7221 [get_ports mcio_dir_45]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.6887 [get_ports mcio_dir_45]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.7947 [get_ports mcio_dir_45]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7742 [get_ports mcio_dir_45]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7992 [get_ports mcio_dir_45_oe]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.7731 [get_ports mcio_dir_45_oe]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.861 [get_ports mcio_dir_45_oe]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.8527 [get_ports mcio_dir_45_oe]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.803 [get_ports mcio_dir_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.7757 [get_ports mcio_dir_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.8808 [get_ports mcio_dir_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.8696 [get_ports mcio_dir_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7101 [get_ports mcio_dir_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.6819 [get_ports mcio_dir_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.7726 [get_ports mcio_dir_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7633 [get_ports mcio_dir_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7571 [get_ports mcio_dir_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.7214 [get_ports mcio_dir_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.8286 [get_ports mcio_dir_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.811 [get_ports mcio_dir_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.8426 [get_ports mcio_dir_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.8061 [get_ports mcio_dir_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.9103 [get_ports mcio_dir_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.8921 [get_ports mcio_dir_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.6908 [get_ports mcio_vio_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.6629 [get_ports mcio_vio_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.754 [get_ports mcio_vio_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7449 [get_ports mcio_vio_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7117 [get_ports mcio_vio_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.6817 [get_ports mcio_vio_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.7874 [get_ports mcio_vio_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.768 [get_ports mcio_vio_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7346 [get_ports mcio_vio_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.6853 [get_ports mcio_vio_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.7921 [get_ports mcio_vio_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7623 [get_ports mcio_vio_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.84 [get_ports mcio_vio_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.8069 [get_ports mcio_vio_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.9169 [get_ports mcio_vio_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.9012 [get_ports mcio_vio_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7344 [get_ports mcio_vio_out[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.6907 [get_ports mcio_vio_out[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.8032 [get_ports mcio_vio_out[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7757 [get_ports mcio_vio_out[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7463 [get_ports mcio_vio_out[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.7036 [get_ports mcio_vio_out[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.8144 [get_ports mcio_vio_out[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7869 [get_ports mcio_vio_out[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7576 [get_ports mcio_vio_out[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.7093 [get_ports mcio_vio_out[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.8245 [get_ports mcio_vio_out[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7918 [get_ports mcio_vio_out[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7316 [get_ports mcio_vio_out[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.693 [get_ports mcio_vio_out[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.8045 [get_ports mcio_vio_out[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7819 [get_ports mcio_vio_out[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7474 [get_ports test[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.7133 [get_ports test[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.8013 [get_ports test[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7827 [get_ports test[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7312 [get_ports test_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.6808 [get_ports test_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.8 [get_ports test_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7664 [get_ports test_oe[2]]
# Boundary pin delays for vp_gpio_s_b2
# Core Data
# Boundary pin delays for vp_pll_nw_2
# Boundary pin delays for vp_pll_sw_2

######################################
# End IO Ring Boundary Delays SDC File
######################################
