#######################################
# ACE GENERATED DELAYS SDC FILE
# Generated on: 2023.06.12 at 14:46:13 PDT
# By: ACE 9.0.1
# From project: vp_project
#######################################
# IO Ring Boundary Delays SDC File
#######################################
# SDC PVT Conditions:
# Voltage: 850 Temperature: 125 Corner: fast
#######################################
# Boundary pin delays for ethernet_0
# Clocks and Resets
set_clock_latency -source -late -rise 0.610886 [get_clocks ethernet_0_m0_ff_clk_divby2]
set_clock_latency -source -early -rise 0.511006 [get_clocks ethernet_0_m0_ff_clk_divby2]
set_clock_latency -source -late -rise 0.649679 [get_clocks ethernet_0_m1_ff_clk_divby2]
set_clock_latency -source -early -rise 0.554636 [get_clocks ethernet_0_m1_ff_clk_divby2]
set_clock_latency -source -late -rise 0.562420 [get_clocks ethernet_0_ref_clk_divby2]
set_clock_latency -source -early -rise 0.510929 [get_clocks ethernet_0_ref_clk_divby2]
# Quad MAC 0 Flow Control
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.1903 [get_ports ethernet_0_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 1.2544 [get_ports ethernet_0_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 1.4173 [get_ports ethernet_0_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 1.4856 [get_ports ethernet_0_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.2416 [get_ports ethernet_0_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 1.3683 [get_ports ethernet_0_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 1.4819 [get_ports ethernet_0_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 1.6174 [get_ports ethernet_0_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.1628 [get_ports ethernet_0_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 1.2341 [get_ports ethernet_0_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 1.3705 [get_ports ethernet_0_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 1.4459 [get_ports ethernet_0_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.2691 [get_ports ethernet_0_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 1.3418 [get_ports ethernet_0_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 1.3934 [get_ports ethernet_0_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 1.4646 [get_ports ethernet_0_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.1692 [get_ports ethernet_0_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 1.2465 [get_ports ethernet_0_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 1.3625 [get_ports ethernet_0_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 1.4462 [get_ports ethernet_0_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.1141 [get_ports ethernet_0_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 1.1706 [get_ports ethernet_0_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 1.3242 [get_ports ethernet_0_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 1.3769 [get_ports ethernet_0_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.1092 [get_ports ethernet_0_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 1.1697 [get_ports ethernet_0_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 1.3262 [get_ports ethernet_0_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 1.3758 [get_ports ethernet_0_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.2543 [get_ports ethernet_0_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 1.3131 [get_ports ethernet_0_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 1.378 [get_ports ethernet_0_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 1.4393 [get_ports ethernet_0_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.2666 [get_ports ethernet_0_quad0_emac_pause_on[8]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.3859 [get_ports ethernet_0_quad0_emac_pause_on[8]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.2087 [get_ports ethernet_0_quad0_emac_pause_on[9]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.2595 [get_ports ethernet_0_quad0_emac_pause_on[9]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.1665 [get_ports ethernet_0_quad0_emac_pause_on[10]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.2224 [get_ports ethernet_0_quad0_emac_pause_on[10]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.1599 [get_ports ethernet_0_quad0_emac_pause_on[11]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.2182 [get_ports ethernet_0_quad0_emac_pause_on[11]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.1702 [get_ports ethernet_0_quad0_emac_pause_on[12]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.2255 [get_ports ethernet_0_quad0_emac_pause_on[12]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.1967 [get_ports ethernet_0_quad0_emac_pause_on[13]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.2589 [get_ports ethernet_0_quad0_emac_pause_on[13]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.1981 [get_ports ethernet_0_quad0_emac_pause_on[14]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.2697 [get_ports ethernet_0_quad0_emac_pause_on[14]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.2972 [get_ports ethernet_0_quad0_emac_pause_on[15]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.419 [get_ports ethernet_0_quad0_emac_pause_on[15]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.2732 [get_ports ethernet_0_quad0_emac_pause_on[16]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.313 [get_ports ethernet_0_quad0_emac_pause_on[16]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.2527 [get_ports ethernet_0_quad0_emac_pause_on[17]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.2905 [get_ports ethernet_0_quad0_emac_pause_on[17]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.3011 [get_ports ethernet_0_quad0_emac_pause_on[18]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.3807 [get_ports ethernet_0_quad0_emac_pause_on[18]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.3041 [get_ports ethernet_0_quad0_emac_pause_on[19]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.3509 [get_ports ethernet_0_quad0_emac_pause_on[19]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.2997 [get_ports ethernet_0_quad0_emac_pause_on[20]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.3606 [get_ports ethernet_0_quad0_emac_pause_on[20]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.3415 [get_ports ethernet_0_quad0_emac_pause_on[21]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.4236 [get_ports ethernet_0_quad0_emac_pause_on[21]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.235 [get_ports ethernet_0_quad0_emac_pause_on[22]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.2754 [get_ports ethernet_0_quad0_emac_pause_on[22]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.2815 [get_ports ethernet_0_quad0_emac_pause_on[23]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.3413 [get_ports ethernet_0_quad0_emac_pause_on[23]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.2301 [get_ports ethernet_0_quad0_emac_pause_on[24]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.2564 [get_ports ethernet_0_quad0_emac_pause_on[24]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.305 [get_ports ethernet_0_quad0_emac_pause_on[25]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.366 [get_ports ethernet_0_quad0_emac_pause_on[25]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.3041 [get_ports ethernet_0_quad0_emac_pause_on[26]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.3567 [get_ports ethernet_0_quad0_emac_pause_on[26]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.2763 [get_ports ethernet_0_quad0_emac_pause_on[27]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.3101 [get_ports ethernet_0_quad0_emac_pause_on[27]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.2716 [get_ports ethernet_0_quad0_emac_pause_on[28]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.3451 [get_ports ethernet_0_quad0_emac_pause_on[28]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.2773 [get_ports ethernet_0_quad0_emac_pause_on[29]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.3368 [get_ports ethernet_0_quad0_emac_pause_on[29]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.2349 [get_ports ethernet_0_quad0_emac_pause_on[30]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.2734 [get_ports ethernet_0_quad0_emac_pause_on[30]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.2658 [get_ports ethernet_0_quad0_emac_pause_on[31]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.3193 [get_ports ethernet_0_quad0_emac_pause_on[31]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.4049 [get_ports ethernet_0_quad0_emac_xoff_gen[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.4238 [get_ports ethernet_0_quad0_emac_xoff_gen[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.3778 [get_ports ethernet_0_quad0_emac_xoff_gen[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.4058 [get_ports ethernet_0_quad0_emac_xoff_gen[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.3861 [get_ports ethernet_0_quad0_emac_xoff_gen[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.4062 [get_ports ethernet_0_quad0_emac_xoff_gen[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.3655 [get_ports ethernet_0_quad0_emac_xoff_gen[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.3748 [get_ports ethernet_0_quad0_emac_xoff_gen[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.3932 [get_ports ethernet_0_quad0_emac_xoff_gen[4]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.4115 [get_ports ethernet_0_quad0_emac_xoff_gen[4]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.5141 [get_ports ethernet_0_quad0_emac_xoff_gen[5]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.5162 [get_ports ethernet_0_quad0_emac_xoff_gen[5]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.3835 [get_ports ethernet_0_quad0_emac_xoff_gen[6]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.3935 [get_ports ethernet_0_quad0_emac_xoff_gen[6]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.3228 [get_ports ethernet_0_quad0_emac_xoff_gen[7]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.3506 [get_ports ethernet_0_quad0_emac_xoff_gen[7]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.1618 [get_ports ethernet_0_quad0_emac_xoff_gen[8]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.1704 [get_ports ethernet_0_quad0_emac_xoff_gen[8]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.1437 [get_ports ethernet_0_quad0_emac_xoff_gen[9]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.1553 [get_ports ethernet_0_quad0_emac_xoff_gen[9]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.1513 [get_ports ethernet_0_quad0_emac_xoff_gen[10]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.1592 [get_ports ethernet_0_quad0_emac_xoff_gen[10]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.1594 [get_ports ethernet_0_quad0_emac_xoff_gen[11]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.1713 [get_ports ethernet_0_quad0_emac_xoff_gen[11]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.1891 [get_ports ethernet_0_quad0_emac_xoff_gen[12]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2045 [get_ports ethernet_0_quad0_emac_xoff_gen[12]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.1838 [get_ports ethernet_0_quad0_emac_xoff_gen[13]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.1963 [get_ports ethernet_0_quad0_emac_xoff_gen[13]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.1715 [get_ports ethernet_0_quad0_emac_xoff_gen[14]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.1804 [get_ports ethernet_0_quad0_emac_xoff_gen[14]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.1486 [get_ports ethernet_0_quad0_emac_xoff_gen[15]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.155 [get_ports ethernet_0_quad0_emac_xoff_gen[15]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.1623 [get_ports ethernet_0_quad0_emac_xoff_gen[16]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.1782 [get_ports ethernet_0_quad0_emac_xoff_gen[16]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2517 [get_ports ethernet_0_quad0_emac_xoff_gen[17]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2654 [get_ports ethernet_0_quad0_emac_xoff_gen[17]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.246 [get_ports ethernet_0_quad0_emac_xoff_gen[18]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2556 [get_ports ethernet_0_quad0_emac_xoff_gen[18]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.3327 [get_ports ethernet_0_quad0_emac_xoff_gen[19]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.3432 [get_ports ethernet_0_quad0_emac_xoff_gen[19]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.1798 [get_ports ethernet_0_quad0_emac_xoff_gen[20]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.1971 [get_ports ethernet_0_quad0_emac_xoff_gen[20]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2521 [get_ports ethernet_0_quad0_emac_xoff_gen[21]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2591 [get_ports ethernet_0_quad0_emac_xoff_gen[21]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.1821 [get_ports ethernet_0_quad0_emac_xoff_gen[22]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.1934 [get_ports ethernet_0_quad0_emac_xoff_gen[22]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.1924 [get_ports ethernet_0_quad0_emac_xoff_gen[23]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2071 [get_ports ethernet_0_quad0_emac_xoff_gen[23]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2659 [get_ports ethernet_0_quad0_emac_xoff_gen[24]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2728 [get_ports ethernet_0_quad0_emac_xoff_gen[24]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.1917 [get_ports ethernet_0_quad0_emac_xoff_gen[25]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2017 [get_ports ethernet_0_quad0_emac_xoff_gen[25]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.1695 [get_ports ethernet_0_quad0_emac_xoff_gen[26]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.1817 [get_ports ethernet_0_quad0_emac_xoff_gen[26]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.1671 [get_ports ethernet_0_quad0_emac_xoff_gen[27]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.1797 [get_ports ethernet_0_quad0_emac_xoff_gen[27]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2121 [get_ports ethernet_0_quad0_emac_xoff_gen[28]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2206 [get_ports ethernet_0_quad0_emac_xoff_gen[28]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2402 [get_ports ethernet_0_quad0_emac_xoff_gen[29]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2471 [get_ports ethernet_0_quad0_emac_xoff_gen[29]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.1874 [get_ports ethernet_0_quad0_emac_xoff_gen[30]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.1922 [get_ports ethernet_0_quad0_emac_xoff_gen[30]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.1597 [get_ports ethernet_0_quad0_emac_xoff_gen[31]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.1711 [get_ports ethernet_0_quad0_emac_xoff_gen[31]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.3014 [get_ports ethernet_0_quad0_lpi_txhold[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.311 [get_ports ethernet_0_quad0_lpi_txhold[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2112 [get_ports ethernet_0_quad0_lpi_txhold[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2205 [get_ports ethernet_0_quad0_lpi_txhold[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2433 [get_ports ethernet_0_quad0_lpi_txhold[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2565 [get_ports ethernet_0_quad0_lpi_txhold[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.1882 [get_ports ethernet_0_quad0_lpi_txhold[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2 [get_ports ethernet_0_quad0_lpi_txhold[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay -0.4787 [get_ports ethernet_0_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay -0.4782 [get_ports ethernet_0_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay -0.621 [get_ports ethernet_0_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay -0.6057 [get_ports ethernet_0_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay -0.5857 [get_ports ethernet_0_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay -0.578 [get_ports ethernet_0_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay -0.5543 [get_ports ethernet_0_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay -0.5347 [get_ports ethernet_0_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay -0.5886 [get_ports ethernet_0_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay -0.5915 [get_ports ethernet_0_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay -0.6543 [get_ports ethernet_0_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay -0.6441 [get_ports ethernet_0_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay -0.6386 [get_ports ethernet_0_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay -0.635 [get_ports ethernet_0_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay -0.6563 [get_ports ethernet_0_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay -0.6416 [get_ports ethernet_0_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.3016 [get_ports ethernet_0_quad0_tx_hold_req[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2929 [get_ports ethernet_0_quad0_tx_hold_req[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.1287 [get_ports ethernet_0_quad0_tx_hold_req[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.1344 [get_ports ethernet_0_quad0_tx_hold_req[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2133 [get_ports ethernet_0_quad0_tx_hold_req[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2192 [get_ports ethernet_0_quad0_tx_hold_req[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.1699 [get_ports ethernet_0_quad0_tx_hold_req[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.1819 [get_ports ethernet_0_quad0_tx_hold_req[3]]
# Quad MAC 0 Status
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.3604 [get_ports ethernet_0_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 1.4099 [get_ports ethernet_0_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.4112 [get_ports ethernet_0_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 1.4647 [get_ports ethernet_0_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.3907 [get_ports ethernet_0_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 1.4314 [get_ports ethernet_0_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.3952 [get_ports ethernet_0_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 1.4386 [get_ports ethernet_0_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 1.3007 [get_ports ethernet_0_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 1.3508 [get_ports ethernet_0_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 1.3414 [get_ports ethernet_0_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 1.3948 [get_ports ethernet_0_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 1.3306 [get_ports ethernet_0_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 1.3706 [get_ports ethernet_0_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 1.3248 [get_ports ethernet_0_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 1.3702 [get_ports ethernet_0_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.3385 [get_ports ethernet_0_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 1.3742 [get_ports ethernet_0_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.3571 [get_ports ethernet_0_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 1.414 [get_ports ethernet_0_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.3347 [get_ports ethernet_0_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 1.374 [get_ports ethernet_0_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.3607 [get_ports ethernet_0_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 1.4046 [get_ports ethernet_0_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 1.2816 [get_ports ethernet_0_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 1.3178 [get_ports ethernet_0_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 1.278 [get_ports ethernet_0_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 1.3355 [get_ports ethernet_0_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 1.2832 [get_ports ethernet_0_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 1.3216 [get_ports ethernet_0_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 1.3058 [get_ports ethernet_0_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 1.3496 [get_ports ethernet_0_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 1.2983 [get_ports ethernet_0_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 1.3446 [get_ports ethernet_0_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 1.2921 [get_ports ethernet_0_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 1.3489 [get_ports ethernet_0_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 1.3483 [get_ports ethernet_0_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 1.373 [get_ports ethernet_0_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 1.2482 [get_ports ethernet_0_m0_mac_tx_underflow[3]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 1.2817 [get_ports ethernet_0_m0_mac_tx_underflow[3]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay 1.2652 [get_ports ethernet_0_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay 1.3112 [get_ports ethernet_0_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay 1.2335 [get_ports ethernet_0_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay 1.2881 [get_ports ethernet_0_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay 1.3048 [get_ports ethernet_0_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay 1.3311 [get_ports ethernet_0_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay 1.2071 [get_ports ethernet_0_m0_mac_tx_underflow[3]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay 1.2416 [get_ports ethernet_0_m0_mac_tx_underflow[3]]
# Boundary pin delays for ethernet_1
# Clocks and Resets
set_clock_latency -source -late -rise 0.618809 [get_clocks ethernet_1_m0_ff_clk_divby2]
set_clock_latency -source -early -rise 0.504572 [get_clocks ethernet_1_m0_ff_clk_divby2]
set_clock_latency -source -late -rise 0.642308 [get_clocks ethernet_1_m1_ff_clk_divby2]
set_clock_latency -source -early -rise 0.547197 [get_clocks ethernet_1_m1_ff_clk_divby2]
set_clock_latency -source -late -rise 0.534643 [get_clocks ethernet_1_ref_clk_divby2]
set_clock_latency -source -early -rise 0.491881 [get_clocks ethernet_1_ref_clk_divby2]
# Quad MAC 0 Flow Control
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 1.3607 [get_ports ethernet_1_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 1.394 [get_ports ethernet_1_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.1338 [get_ports ethernet_1_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.1628 [get_ports ethernet_1_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 1.3082 [get_ports ethernet_1_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 1.3465 [get_ports ethernet_1_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.0678 [get_ports ethernet_1_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.0974 [get_ports ethernet_1_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 1.3094 [get_ports ethernet_1_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 1.3442 [get_ports ethernet_1_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.1017 [get_ports ethernet_1_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.1324 [get_ports ethernet_1_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 1.3222 [get_ports ethernet_1_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 1.3542 [get_ports ethernet_1_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.1979 [get_ports ethernet_1_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.2314 [get_ports ethernet_1_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 1.3067 [get_ports ethernet_1_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 1.3486 [get_ports ethernet_1_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.1135 [get_ports ethernet_1_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.149 [get_ports ethernet_1_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 1.314 [get_ports ethernet_1_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 1.3589 [get_ports ethernet_1_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.1039 [get_ports ethernet_1_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.1526 [get_ports ethernet_1_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 1.3002 [get_ports ethernet_1_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 1.3295 [get_ports ethernet_1_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.0832 [get_ports ethernet_1_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.1234 [get_ports ethernet_1_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 1.3245 [get_ports ethernet_1_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 1.3544 [get_ports ethernet_1_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.2008 [get_ports ethernet_1_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.2281 [get_ports ethernet_1_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.1361 [get_ports ethernet_1_quad0_emac_pause_on[8]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.1666 [get_ports ethernet_1_quad0_emac_pause_on[8]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.1628 [get_ports ethernet_1_quad0_emac_pause_on[9]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.186 [get_ports ethernet_1_quad0_emac_pause_on[9]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.1334 [get_ports ethernet_1_quad0_emac_pause_on[10]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.1636 [get_ports ethernet_1_quad0_emac_pause_on[10]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.1174 [get_ports ethernet_1_quad0_emac_pause_on[11]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.1447 [get_ports ethernet_1_quad0_emac_pause_on[11]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.1281 [get_ports ethernet_1_quad0_emac_pause_on[12]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.1557 [get_ports ethernet_1_quad0_emac_pause_on[12]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.1355 [get_ports ethernet_1_quad0_emac_pause_on[13]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.1644 [get_ports ethernet_1_quad0_emac_pause_on[13]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.1444 [get_ports ethernet_1_quad0_emac_pause_on[14]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.18 [get_ports ethernet_1_quad0_emac_pause_on[14]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.161 [get_ports ethernet_1_quad0_emac_pause_on[15]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.188 [get_ports ethernet_1_quad0_emac_pause_on[15]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.2228 [get_ports ethernet_1_quad0_emac_pause_on[16]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.2316 [get_ports ethernet_1_quad0_emac_pause_on[16]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.2139 [get_ports ethernet_1_quad0_emac_pause_on[17]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.2214 [get_ports ethernet_1_quad0_emac_pause_on[17]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.2037 [get_ports ethernet_1_quad0_emac_pause_on[18]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.2182 [get_ports ethernet_1_quad0_emac_pause_on[18]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.2683 [get_ports ethernet_1_quad0_emac_pause_on[19]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.2827 [get_ports ethernet_1_quad0_emac_pause_on[19]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.22 [get_ports ethernet_1_quad0_emac_pause_on[20]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.2396 [get_ports ethernet_1_quad0_emac_pause_on[20]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.2676 [get_ports ethernet_1_quad0_emac_pause_on[21]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3004 [get_ports ethernet_1_quad0_emac_pause_on[21]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.1987 [get_ports ethernet_1_quad0_emac_pause_on[22]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.2168 [get_ports ethernet_1_quad0_emac_pause_on[22]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.2284 [get_ports ethernet_1_quad0_emac_pause_on[23]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.2327 [get_ports ethernet_1_quad0_emac_pause_on[23]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.2247 [get_ports ethernet_1_quad0_emac_pause_on[24]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.2446 [get_ports ethernet_1_quad0_emac_pause_on[24]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.233 [get_ports ethernet_1_quad0_emac_pause_on[25]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.2443 [get_ports ethernet_1_quad0_emac_pause_on[25]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.2295 [get_ports ethernet_1_quad0_emac_pause_on[26]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.2391 [get_ports ethernet_1_quad0_emac_pause_on[26]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.235 [get_ports ethernet_1_quad0_emac_pause_on[27]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.2406 [get_ports ethernet_1_quad0_emac_pause_on[27]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.2117 [get_ports ethernet_1_quad0_emac_pause_on[28]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.2424 [get_ports ethernet_1_quad0_emac_pause_on[28]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.2381 [get_ports ethernet_1_quad0_emac_pause_on[29]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.2671 [get_ports ethernet_1_quad0_emac_pause_on[29]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.2298 [get_ports ethernet_1_quad0_emac_pause_on[30]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.2612 [get_ports ethernet_1_quad0_emac_pause_on[30]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.2107 [get_ports ethernet_1_quad0_emac_pause_on[31]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.2251 [get_ports ethernet_1_quad0_emac_pause_on[31]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.384 [get_ports ethernet_1_quad0_emac_xoff_gen[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.4032 [get_ports ethernet_1_quad0_emac_xoff_gen[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.3425 [get_ports ethernet_1_quad0_emac_xoff_gen[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.3712 [get_ports ethernet_1_quad0_emac_xoff_gen[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.363 [get_ports ethernet_1_quad0_emac_xoff_gen[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.3835 [get_ports ethernet_1_quad0_emac_xoff_gen[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.3552 [get_ports ethernet_1_quad0_emac_xoff_gen[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.3646 [get_ports ethernet_1_quad0_emac_xoff_gen[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.3767 [get_ports ethernet_1_quad0_emac_xoff_gen[4]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.3955 [get_ports ethernet_1_quad0_emac_xoff_gen[4]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.4156 [get_ports ethernet_1_quad0_emac_xoff_gen[5]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.4188 [get_ports ethernet_1_quad0_emac_xoff_gen[5]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.3664 [get_ports ethernet_1_quad0_emac_xoff_gen[6]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.3772 [get_ports ethernet_1_quad0_emac_xoff_gen[6]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.3109 [get_ports ethernet_1_quad0_emac_xoff_gen[7]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.3384 [get_ports ethernet_1_quad0_emac_xoff_gen[7]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1419 [get_ports ethernet_1_quad0_emac_xoff_gen[8]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.1512 [get_ports ethernet_1_quad0_emac_xoff_gen[8]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1367 [get_ports ethernet_1_quad0_emac_xoff_gen[9]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.148 [get_ports ethernet_1_quad0_emac_xoff_gen[9]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1342 [get_ports ethernet_1_quad0_emac_xoff_gen[10]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.1426 [get_ports ethernet_1_quad0_emac_xoff_gen[10]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1473 [get_ports ethernet_1_quad0_emac_xoff_gen[11]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.1592 [get_ports ethernet_1_quad0_emac_xoff_gen[11]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1251 [get_ports ethernet_1_quad0_emac_xoff_gen[12]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.1416 [get_ports ethernet_1_quad0_emac_xoff_gen[12]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1632 [get_ports ethernet_1_quad0_emac_xoff_gen[13]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.1757 [get_ports ethernet_1_quad0_emac_xoff_gen[13]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1494 [get_ports ethernet_1_quad0_emac_xoff_gen[14]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.159 [get_ports ethernet_1_quad0_emac_xoff_gen[14]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1228 [get_ports ethernet_1_quad0_emac_xoff_gen[15]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.1298 [get_ports ethernet_1_quad0_emac_xoff_gen[15]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1491 [get_ports ethernet_1_quad0_emac_xoff_gen[16]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.1655 [get_ports ethernet_1_quad0_emac_xoff_gen[16]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1802 [get_ports ethernet_1_quad0_emac_xoff_gen[17]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.1945 [get_ports ethernet_1_quad0_emac_xoff_gen[17]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1647 [get_ports ethernet_1_quad0_emac_xoff_gen[18]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.1759 [get_ports ethernet_1_quad0_emac_xoff_gen[18]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1703 [get_ports ethernet_1_quad0_emac_xoff_gen[19]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.1822 [get_ports ethernet_1_quad0_emac_xoff_gen[19]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1732 [get_ports ethernet_1_quad0_emac_xoff_gen[20]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.1906 [get_ports ethernet_1_quad0_emac_xoff_gen[20]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1644 [get_ports ethernet_1_quad0_emac_xoff_gen[21]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.1725 [get_ports ethernet_1_quad0_emac_xoff_gen[21]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.159 [get_ports ethernet_1_quad0_emac_xoff_gen[22]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.1706 [get_ports ethernet_1_quad0_emac_xoff_gen[22]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1597 [get_ports ethernet_1_quad0_emac_xoff_gen[23]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.1754 [get_ports ethernet_1_quad0_emac_xoff_gen[23]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1882 [get_ports ethernet_1_quad0_emac_xoff_gen[24]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.1962 [get_ports ethernet_1_quad0_emac_xoff_gen[24]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1537 [get_ports ethernet_1_quad0_emac_xoff_gen[25]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.1645 [get_ports ethernet_1_quad0_emac_xoff_gen[25]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1422 [get_ports ethernet_1_quad0_emac_xoff_gen[26]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.1546 [get_ports ethernet_1_quad0_emac_xoff_gen[26]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1517 [get_ports ethernet_1_quad0_emac_xoff_gen[27]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.1647 [get_ports ethernet_1_quad0_emac_xoff_gen[27]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1555 [get_ports ethernet_1_quad0_emac_xoff_gen[28]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.1642 [get_ports ethernet_1_quad0_emac_xoff_gen[28]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1751 [get_ports ethernet_1_quad0_emac_xoff_gen[29]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.1832 [get_ports ethernet_1_quad0_emac_xoff_gen[29]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1727 [get_ports ethernet_1_quad0_emac_xoff_gen[30]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.1779 [get_ports ethernet_1_quad0_emac_xoff_gen[30]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1504 [get_ports ethernet_1_quad0_emac_xoff_gen[31]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.1617 [get_ports ethernet_1_quad0_emac_xoff_gen[31]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2901 [get_ports ethernet_1_quad0_lpi_txhold[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2999 [get_ports ethernet_1_quad0_lpi_txhold[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1362 [get_ports ethernet_1_quad0_lpi_txhold[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.1465 [get_ports ethernet_1_quad0_lpi_txhold[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1861 [get_ports ethernet_1_quad0_lpi_txhold[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2001 [get_ports ethernet_1_quad0_lpi_txhold[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1287 [get_ports ethernet_1_quad0_lpi_txhold[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.1416 [get_ports ethernet_1_quad0_lpi_txhold[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay -0.5958 [get_ports ethernet_1_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay -0.5936 [get_ports ethernet_1_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay -0.6415 [get_ports ethernet_1_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay -0.6255 [get_ports ethernet_1_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay -0.6539 [get_ports ethernet_1_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay -0.6448 [get_ports ethernet_1_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay -0.6332 [get_ports ethernet_1_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay -0.6125 [get_ports ethernet_1_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay -0.6398 [get_ports ethernet_1_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay -0.641 [get_ports ethernet_1_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay -0.6682 [get_ports ethernet_1_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay -0.6576 [get_ports ethernet_1_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay -0.678 [get_ports ethernet_1_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay -0.6731 [get_ports ethernet_1_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay -0.6863 [get_ports ethernet_1_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay -0.6704 [get_ports ethernet_1_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2306 [get_ports ethernet_1_quad0_tx_hold_req[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.223 [get_ports ethernet_1_quad0_tx_hold_req[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1152 [get_ports ethernet_1_quad0_tx_hold_req[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.1214 [get_ports ethernet_1_quad0_tx_hold_req[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1837 [get_ports ethernet_1_quad0_tx_hold_req[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.1901 [get_ports ethernet_1_quad0_tx_hold_req[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1311 [get_ports ethernet_1_quad0_tx_hold_req[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.1437 [get_ports ethernet_1_quad0_tx_hold_req[3]]
# Quad MAC 0 Status
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.3373 [get_ports ethernet_1_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.3677 [get_ports ethernet_1_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.3702 [get_ports ethernet_1_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.3929 [get_ports ethernet_1_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.3671 [get_ports ethernet_1_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.3885 [get_ports ethernet_1_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.3691 [get_ports ethernet_1_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.3884 [get_ports ethernet_1_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 1.2798 [get_ports ethernet_1_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 1.3113 [get_ports ethernet_1_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 1.3173 [get_ports ethernet_1_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 1.3397 [get_ports ethernet_1_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 1.308 [get_ports ethernet_1_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 1.3298 [get_ports ethernet_1_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 1.3019 [get_ports ethernet_1_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 1.3245 [get_ports ethernet_1_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.3294 [get_ports ethernet_1_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.3583 [get_ports ethernet_1_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.3088 [get_ports ethernet_1_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.331 [get_ports ethernet_1_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.3268 [get_ports ethernet_1_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.3603 [get_ports ethernet_1_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.3355 [get_ports ethernet_1_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.3567 [get_ports ethernet_1_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 1.2722 [get_ports ethernet_1_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 1.302 [get_ports ethernet_1_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 1.2562 [get_ports ethernet_1_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 1.2791 [get_ports ethernet_1_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 1.2757 [get_ports ethernet_1_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 1.3085 [get_ports ethernet_1_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 1.2823 [get_ports ethernet_1_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 1.3034 [get_ports ethernet_1_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 1.2631 [get_ports ethernet_1_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 1.276 [get_ports ethernet_1_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 1.2511 [get_ports ethernet_1_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 1.2774 [get_ports ethernet_1_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 1.3322 [get_ports ethernet_1_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 1.3482 [get_ports ethernet_1_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 1.2377 [get_ports ethernet_1_m0_mac_tx_underflow[3]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 1.263 [get_ports ethernet_1_m0_mac_tx_underflow[3]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay 1.2318 [get_ports ethernet_1_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay 1.2462 [get_ports ethernet_1_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay 1.2127 [get_ports ethernet_1_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay 1.2366 [get_ports ethernet_1_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay 1.2978 [get_ports ethernet_1_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay 1.315 [get_ports ethernet_1_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay 1.1973 [get_ports ethernet_1_m0_mac_tx_underflow[3]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay 1.2243 [get_ports ethernet_1_m0_mac_tx_underflow[3]]
# Boundary pin delays for noc
# Boundary pin delays for pll_ddr
# Boundary pin delays for pll_eth_sys_ne_0
# Boundary pin delays for pll_eth_usr_ne_3
# Boundary pin delays for pll_gddr_SE
# Boundary pin delays for pll_gddr_SW
# Boundary pin delays for pll_noc_ne_1
# Boundary pin delays for pll_pcie
# Boundary pin delays for vp_clkio_ne
# Boundary pin delays for vp_clkio_nw
# Boundary pin delays for vp_clkio_se
# Boundary pin delays for vp_clkio_sw
# Boundary pin delays for vp_gpio_n_b0
# Core Data
# Boundary pin delays for vp_gpio_n_b1
# Core Data
# Boundary pin delays for vp_gpio_n_b2
# Core Data
# Boundary pin delays for vp_gpio_s_b0
# Core Data
# Boundary pin delays for vp_gpio_s_b1
# Core Clock
set_clock_latency -source -late -rise 0.226074 [get_clocks mcio_vio_45_10_clk]
set_clock_latency -source -early -rise 0.210574 [get_clocks mcio_vio_45_10_clk]
# Core Data
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay 1.2375 [get_ports mcio_vio_in[0]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay 1.2384 [get_ports mcio_vio_in[0]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay 1.0429 [get_ports mcio_vio_in[0]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay 1.0626 [get_ports mcio_vio_in[0]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay 1.1931 [get_ports mcio_vio_in[1]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay 1.2046 [get_ports mcio_vio_in[1]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay 1.067 [get_ports mcio_vio_in[1]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay 1.0888 [get_ports mcio_vio_in[1]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay 1.1854 [get_ports mcio_vio_in[2]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay 1.1956 [get_ports mcio_vio_in[2]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay 1.0493 [get_ports mcio_vio_in[2]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay 1.0645 [get_ports mcio_vio_in[2]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay 1.2502 [get_ports mcio_vio_in[3]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay 1.2401 [get_ports mcio_vio_in[3]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay 1.0524 [get_ports mcio_vio_in[3]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay 1.0761 [get_ports mcio_vio_in[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.4845 [get_ports mcio_dir[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.4796 [get_ports mcio_dir[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.5388 [get_ports mcio_dir[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.5344 [get_ports mcio_dir[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.4941 [get_ports mcio_dir[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.4723 [get_ports mcio_dir[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.5565 [get_ports mcio_dir[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.537 [get_ports mcio_dir[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.4966 [get_ports mcio_dir[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.4722 [get_ports mcio_dir[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.5501 [get_ports mcio_dir[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.5285 [get_ports mcio_dir[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.4944 [get_ports mcio_dir[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.4717 [get_ports mcio_dir[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.5459 [get_ports mcio_dir[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.5258 [get_ports mcio_dir[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.4822 [get_ports mcio_dir_45]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.4684 [get_ports mcio_dir_45]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.5495 [get_ports mcio_dir_45]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.5351 [get_ports mcio_dir_45]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.5325 [get_ports mcio_dir_45_oe]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.5198 [get_ports mcio_dir_45_oe]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.585 [get_ports mcio_dir_45_oe]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.5748 [get_ports mcio_dir_45_oe]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.5079 [get_ports mcio_dir_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.4928 [get_ports mcio_dir_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.5836 [get_ports mcio_dir_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.5699 [get_ports mcio_dir_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.4664 [get_ports mcio_dir_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.4531 [get_ports mcio_dir_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.5199 [get_ports mcio_dir_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.5098 [get_ports mcio_dir_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.4862 [get_ports mcio_dir_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.4678 [get_ports mcio_dir_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.5579 [get_ports mcio_dir_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.5411 [get_ports mcio_dir_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.5408 [get_ports mcio_dir_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.5241 [get_ports mcio_dir_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.6018 [get_ports mcio_dir_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.5879 [get_ports mcio_dir_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.457 [get_ports mcio_vio_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.4402 [get_ports mcio_vio_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.5134 [get_ports mcio_vio_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.4981 [get_ports mcio_vio_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.4803 [get_ports mcio_vio_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.4654 [get_ports mcio_vio_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.549 [get_ports mcio_vio_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.5347 [get_ports mcio_vio_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.4867 [get_ports mcio_vio_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.4617 [get_ports mcio_vio_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.5374 [get_ports mcio_vio_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.5153 [get_ports mcio_vio_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.5525 [get_ports mcio_vio_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.5351 [get_ports mcio_vio_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.62 [get_ports mcio_vio_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.6048 [get_ports mcio_vio_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.5025 [get_ports mcio_vio_out[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.4799 [get_ports mcio_vio_out[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.5597 [get_ports mcio_vio_out[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.54 [get_ports mcio_vio_out[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.506 [get_ports mcio_vio_out[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.4845 [get_ports mcio_vio_out[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.5643 [get_ports mcio_vio_out[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.5444 [get_ports mcio_vio_out[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.5017 [get_ports mcio_vio_out[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.4796 [get_ports mcio_vio_out[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.5567 [get_ports mcio_vio_out[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.5362 [get_ports mcio_vio_out[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.4919 [get_ports mcio_vio_out[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.4715 [get_ports mcio_vio_out[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.5582 [get_ports mcio_vio_out[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.5393 [get_ports mcio_vio_out[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.486 [get_ports test[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.4706 [get_ports test[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.5324 [get_ports test[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.5179 [get_ports test[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.47 [get_ports test_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.4453 [get_ports test_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.5373 [get_ports test_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.5145 [get_ports test_oe[2]]
# Boundary pin delays for vp_gpio_s_b2
# Core Data
# Boundary pin delays for vp_pll_nw_2
# Boundary pin delays for vp_pll_sw_2

######################################
# End IO Ring Boundary Delays SDC File
######################################
