#######################################
# ACE GENERATED DELAYS SDC FILE
# Generated on: 2023.06.12 at 14:46:13 PDT
# By: ACE 9.0.1
# From project: vp_project
#######################################
# IO Ring Boundary Delays SDC File
#######################################
# SDC PVT Conditions:
# Voltage: 850 Temperature: 0 Corner: fast
#######################################
# Boundary pin delays for ethernet_0
# Clocks and Resets
set_clock_latency -source -late -rise 0.55139738 [get_clocks ethernet_0_m0_ff_clk_divby2]
set_clock_latency -source -early -rise 0.4764574 [get_clocks ethernet_0_m0_ff_clk_divby2]
set_clock_latency -source -late -rise 0.59865124 [get_clocks ethernet_0_m1_ff_clk_divby2]
set_clock_latency -source -early -rise 0.52191952 [get_clocks ethernet_0_m1_ff_clk_divby2]
set_clock_latency -source -late -rise 0.50751591 [get_clocks ethernet_0_ref_clk_divby2]
set_clock_latency -source -early -rise 0.4656605 [get_clocks ethernet_0_ref_clk_divby2]
# Quad MAC 0 Flow Control
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 1.337543 [get_ports ethernet_0_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 1.380165 [get_ports ethernet_0_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.116454 [get_ports ethernet_0_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 1.158268 [get_ports ethernet_0_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 1.396931 [get_ports ethernet_0_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 1.463086 [get_ports ethernet_0_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.161197 [get_ports ethernet_0_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 1.223514 [get_ports ethernet_0_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 1.295123 [get_ports ethernet_0_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 1.330473 [get_ports ethernet_0_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.095749 [get_ports ethernet_0_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 1.12817 [get_ports ethernet_0_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 1.302597 [get_ports ethernet_0_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 1.336533 [get_ports ethernet_0_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.182811 [get_ports ethernet_0_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 1.217555 [get_ports ethernet_0_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 1.288053 [get_ports ethernet_0_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 1.325827 [get_ports ethernet_0_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.1009 [get_ports ethernet_0_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 1.135947 [get_ports ethernet_0_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 1.243613 [get_ports ethernet_0_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 1.294517 [get_ports ethernet_0_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.041714 [get_ports ethernet_0_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 1.094234 [get_ports ethernet_0_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 1.244724 [get_ports ethernet_0_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 1.283811 [get_ports ethernet_0_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.038987 [get_ports ethernet_0_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 1.087366 [get_ports ethernet_0_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 1.298052 [get_ports ethernet_0_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 1.326635 [get_ports ethernet_0_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.176751 [get_ports ethernet_0_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 1.203516 [get_ports ethernet_0_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.229573 [get_ports ethernet_0_quad0_emac_pause_on[8]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.301485 [get_ports ethernet_0_quad0_emac_pause_on[8]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.178366 [get_ports ethernet_0_quad0_emac_pause_on[9]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.208868 [get_ports ethernet_0_quad0_emac_pause_on[9]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.14342 [get_ports ethernet_0_quad0_emac_pause_on[10]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.178063 [get_ports ethernet_0_quad0_emac_pause_on[10]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.138572 [get_ports ethernet_0_quad0_emac_pause_on[11]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.173215 [get_ports ethernet_0_quad0_emac_pause_on[11]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.145945 [get_ports ethernet_0_quad0_emac_pause_on[12]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.180588 [get_ports ethernet_0_quad0_emac_pause_on[12]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.164327 [get_ports ethernet_0_quad0_emac_pause_on[13]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.202404 [get_ports ethernet_0_quad0_emac_pause_on[13]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.168367 [get_ports ethernet_0_quad0_emac_pause_on[14]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.210383 [get_ports ethernet_0_quad0_emac_pause_on[14]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.255934 [get_ports ethernet_0_quad0_emac_pause_on[15]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.327644 [get_ports ethernet_0_quad0_emac_pause_on[15]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.235128 [get_ports ethernet_0_quad0_emac_pause_on[16]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.252702 [get_ports ethernet_0_quad0_emac_pause_on[16]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.223412 [get_ports ethernet_0_quad0_emac_pause_on[17]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.238764 [get_ports ethernet_0_quad0_emac_pause_on[17]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.264115 [get_ports ethernet_0_quad0_emac_pause_on[18]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.309666 [get_ports ethernet_0_quad0_emac_pause_on[18]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.275023 [get_ports ethernet_0_quad0_emac_pause_on[19]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.29694 [get_ports ethernet_0_quad0_emac_pause_on[19]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.251591 [get_ports ethernet_0_quad0_emac_pause_on[20]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.286436 [get_ports ethernet_0_quad0_emac_pause_on[20]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.300475 [get_ports ethernet_0_quad0_emac_pause_on[21]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.343097 [get_ports ethernet_0_quad0_emac_pause_on[21]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.199172 [get_ports ethernet_0_quad0_emac_pause_on[22]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.223311 [get_ports ethernet_0_quad0_emac_pause_on[22]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.254318 [get_ports ethernet_0_quad0_emac_pause_on[23]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.283709 [get_ports ethernet_0_quad0_emac_pause_on[23]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.206747 [get_ports ethernet_0_quad0_emac_pause_on[24]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.22422 [get_ports ethernet_0_quad0_emac_pause_on[24]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.26563 [get_ports ethernet_0_quad0_emac_pause_on[25]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.293506 [get_ports ethernet_0_quad0_emac_pause_on[25]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.259671 [get_ports ethernet_0_quad0_emac_pause_on[26]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.286032 [get_ports ethernet_0_quad0_emac_pause_on[26]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.2424 [get_ports ethernet_0_quad0_emac_pause_on[27]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.256439 [get_ports ethernet_0_quad0_emac_pause_on[27]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.236946 [get_ports ethernet_0_quad0_emac_pause_on[28]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.282497 [get_ports ethernet_0_quad0_emac_pause_on[28]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.245228 [get_ports ethernet_0_quad0_emac_pause_on[29]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.282396 [get_ports ethernet_0_quad0_emac_pause_on[29]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.212504 [get_ports ethernet_0_quad0_emac_pause_on[30]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.241895 [get_ports ethernet_0_quad0_emac_pause_on[30]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.231997 [get_ports ethernet_0_quad0_emac_pause_on[31]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.260681 [get_ports ethernet_0_quad0_emac_pause_on[31]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.364004 [get_ports ethernet_0_quad0_emac_xoff_gen[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.384103 [get_ports ethernet_0_quad0_emac_xoff_gen[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.335017 [get_ports ethernet_0_quad0_emac_xoff_gen[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.363701 [get_ports ethernet_0_quad0_emac_xoff_gen[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.348046 [get_ports ethernet_0_quad0_emac_xoff_gen[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.369458 [get_ports ethernet_0_quad0_emac_xoff_gen[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.326836 [get_ports ethernet_0_quad0_emac_xoff_gen[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.34239 [get_ports ethernet_0_quad0_emac_xoff_gen[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.351379 [get_ports ethernet_0_quad0_emac_xoff_gen[4]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.371377 [get_ports ethernet_0_quad0_emac_xoff_gen[4]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.44743 [get_ports ethernet_0_quad0_emac_xoff_gen[5]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.457328 [get_ports ethernet_0_quad0_emac_xoff_gen[5]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.344309 [get_ports ethernet_0_quad0_emac_xoff_gen[6]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.36057 [get_ports ethernet_0_quad0_emac_xoff_gen[6]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.292496 [get_ports ethernet_0_quad0_emac_xoff_gen[7]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.321887 [get_ports ethernet_0_quad0_emac_xoff_gen[7]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.139986 [get_ports ethernet_0_quad0_emac_xoff_gen[8]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.152611 [get_ports ethernet_0_quad0_emac_xoff_gen[8]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.128573 [get_ports ethernet_0_quad0_emac_xoff_gen[9]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.142814 [get_ports ethernet_0_quad0_emac_xoff_gen[9]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.133825 [get_ports ethernet_0_quad0_emac_xoff_gen[10]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.145541 [get_ports ethernet_0_quad0_emac_xoff_gen[10]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.139683 [get_ports ethernet_0_quad0_emac_xoff_gen[11]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.155035 [get_ports ethernet_0_quad0_emac_xoff_gen[11]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.153621 [get_ports ethernet_0_quad0_emac_xoff_gen[12]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.173417 [get_ports ethernet_0_quad0_emac_xoff_gen[12]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.159681 [get_ports ethernet_0_quad0_emac_xoff_gen[13]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.176043 [get_ports ethernet_0_quad0_emac_xoff_gen[13]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.14948 [get_ports ethernet_0_quad0_emac_xoff_gen[14]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.161095 [get_ports ethernet_0_quad0_emac_xoff_gen[14]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.124331 [get_ports ethernet_0_quad0_emac_xoff_gen[15]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.137461 [get_ports ethernet_0_quad0_emac_xoff_gen[15]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.144026 [get_ports ethernet_0_quad0_emac_xoff_gen[16]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.160792 [get_ports ethernet_0_quad0_emac_xoff_gen[16]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.208464 [get_ports ethernet_0_quad0_emac_xoff_gen[17]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.22523 [get_ports ethernet_0_quad0_emac_xoff_gen[17]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.204121 [get_ports ethernet_0_quad0_emac_xoff_gen[18]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.218261 [get_ports ethernet_0_quad0_emac_xoff_gen[18]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.276639 [get_ports ethernet_0_quad0_emac_xoff_gen[19]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.293405 [get_ports ethernet_0_quad0_emac_xoff_gen[19]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.160186 [get_ports ethernet_0_quad0_emac_xoff_gen[20]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.179376 [get_ports ethernet_0_quad0_emac_xoff_gen[20]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.215938 [get_ports ethernet_0_quad0_emac_xoff_gen[21]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.227351 [get_ports ethernet_0_quad0_emac_xoff_gen[21]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.16059 [get_ports ethernet_0_quad0_emac_xoff_gen[22]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.17372 [get_ports ethernet_0_quad0_emac_xoff_gen[22]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.163317 [get_ports ethernet_0_quad0_emac_xoff_gen[23]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.181093 [get_ports ethernet_0_quad0_emac_xoff_gen[23]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.216746 [get_ports ethernet_0_quad0_emac_xoff_gen[24]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.228664 [get_ports ethernet_0_quad0_emac_xoff_gen[24]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.161802 [get_ports ethernet_0_quad0_emac_xoff_gen[25]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.175437 [get_ports ethernet_0_quad0_emac_xoff_gen[25]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.14544 [get_ports ethernet_0_quad0_emac_xoff_gen[26]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.15958 [get_ports ethernet_0_quad0_emac_xoff_gen[26]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.148066 [get_ports ethernet_0_quad0_emac_xoff_gen[27]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.163014 [get_ports ethernet_0_quad0_emac_xoff_gen[27]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.175639 [get_ports ethernet_0_quad0_emac_xoff_gen[28]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.187456 [get_ports ethernet_0_quad0_emac_xoff_gen[28]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.198869 [get_ports ethernet_0_quad0_emac_xoff_gen[29]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.213413 [get_ports ethernet_0_quad0_emac_xoff_gen[29]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.159479 [get_ports ethernet_0_quad0_emac_xoff_gen[30]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.170589 [get_ports ethernet_0_quad0_emac_xoff_gen[30]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.142208 [get_ports ethernet_0_quad0_emac_xoff_gen[31]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.156045 [get_ports ethernet_0_quad0_emac_xoff_gen[31]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.262499 [get_ports ethernet_0_quad0_lpi_txhold[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.278962 [get_ports ethernet_0_quad0_lpi_txhold[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.173013 [get_ports ethernet_0_quad0_lpi_txhold[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.186648 [get_ports ethernet_0_quad0_lpi_txhold[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.203919 [get_ports ethernet_0_quad0_lpi_txhold[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.221291 [get_ports ethernet_0_quad0_lpi_txhold[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.158166 [get_ports ethernet_0_quad0_lpi_txhold[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.174023 [get_ports ethernet_0_quad0_lpi_txhold[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay -0.471165 [get_ports ethernet_0_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay -0.462378 [get_ports ethernet_0_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay -0.586103 [get_ports ethernet_0_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay -0.570246 [get_ports ethernet_0_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay -0.562368 [get_ports ethernet_0_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay -0.548733 [get_ports ethernet_0_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay -0.540855 [get_ports ethernet_0_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay -0.519847 [get_ports ethernet_0_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay -0.558429 [get_ports ethernet_0_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay -0.554389 [get_ports ethernet_0_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay -0.615292 [get_ports ethernet_0_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay -0.604182 [get_ports ethernet_0_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay -0.603576 [get_ports ethernet_0_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay -0.594789 [get_ports ethernet_0_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay -0.616504 [get_ports ethernet_0_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay -0.599637 [get_ports ethernet_0_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.257348 [get_ports ethernet_0_quad0_tx_hold_req[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.25553 [get_ports ethernet_0_quad0_tx_hold_req[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.110292 [get_ports ethernet_0_quad0_tx_hold_req[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.122715 [get_ports ethernet_0_quad0_tx_hold_req[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.18281 [get_ports ethernet_0_quad0_tx_hold_req[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.193718 [get_ports ethernet_0_quad0_tx_hold_req[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.144127 [get_ports ethernet_0_quad0_tx_hold_req[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.159984 [get_ports ethernet_0_quad0_tx_hold_req[3]]
# Quad MAC 0 Status
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.265025 [get_ports ethernet_0_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 1.300072 [get_ports ethernet_0_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.316131 [get_ports ethernet_0_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 1.341583 [get_ports ethernet_0_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.301991 [get_ports ethernet_0_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 1.323201 [get_ports ethernet_0_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.301082 [get_ports ethernet_0_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 1.319666 [get_ports ethernet_0_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 1.211192 [get_ports ethernet_0_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 1.245431 [get_ports ethernet_0_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 1.254824 [get_ports ethernet_0_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 1.280882 [get_ports ethernet_0_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 1.245936 [get_ports ethernet_0_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 1.267752 [get_ports ethernet_0_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 1.237048 [get_ports ethernet_0_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 1.258965 [get_ports ethernet_0_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.253107 [get_ports ethernet_0_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 1.280377 [get_ports ethernet_0_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.261591 [get_ports ethernet_0_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 1.288457 [get_ports ethernet_0_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.251794 [get_ports ethernet_0_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 1.280781 [get_ports ethernet_0_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.268358 [get_ports ethernet_0_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 1.287952 [get_ports ethernet_0_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 1.199577 [get_ports ethernet_0_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 1.227857 [get_ports ethernet_0_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 1.193618 [get_ports ethernet_0_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 1.222706 [get_ports ethernet_0_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 1.203011 [get_ports ethernet_0_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 1.231594 [get_ports ethernet_0_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 1.217555 [get_ports ethernet_0_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 1.237553 [get_ports ethernet_0_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 1.207657 [get_ports ethernet_0_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 1.222302 [get_ports ethernet_0_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 1.198365 [get_ports ethernet_0_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 1.233412 [get_ports ethernet_0_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 1.265631 [get_ports ethernet_0_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 1.271489 [get_ports ethernet_0_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 1.160692 [get_ports ethernet_0_m0_mac_tx_underflow[3]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 1.185437 [get_ports ethernet_0_m0_mac_tx_underflow[3]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay 1.178872 [get_ports ethernet_0_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay 1.195436 [get_ports ethernet_0_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay 1.149481 [get_ports ethernet_0_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay 1.184225 [get_ports ethernet_0_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay 1.228463 [get_ports ethernet_0_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay 1.235937 [get_ports ethernet_0_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay 1.125948 [get_ports ethernet_0_m0_mac_tx_underflow[3]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay 1.153117 [get_ports ethernet_0_m0_mac_tx_underflow[3]]
# Boundary pin delays for ethernet_1
# Clocks and Resets
set_clock_latency -source -late -rise 0.56131457 [get_clocks ethernet_1_m0_ff_clk_divby2]
set_clock_latency -source -early -rise 0.47033983 [get_clocks ethernet_1_m0_ff_clk_divby2]
set_clock_latency -source -late -rise 0.6008894 [get_clocks ethernet_1_m1_ff_clk_divby2]
set_clock_latency -source -early -rise 0.51323251 [get_clocks ethernet_1_m1_ff_clk_divby2]
set_clock_latency -source -late -rise 0.4866584 [get_clocks ethernet_1_ref_clk_divby2]
set_clock_latency -source -early -rise 0.45106196 [get_clocks ethernet_1_ref_clk_divby2]
# Quad MAC 0 Flow Control
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 1.294921 [get_ports ethernet_1_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 1.3231 [get_ports ethernet_1_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.073933 [get_ports ethernet_1_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.101203 [get_ports ethernet_1_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 1.256339 [get_ports ethernet_1_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 1.272297 [get_ports ethernet_1_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.020504 [get_ports ethernet_1_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.032624 [get_ports ethernet_1_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 1.248461 [get_ports ethernet_1_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 1.26654 [get_ports ethernet_1_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.049188 [get_ports ethernet_1_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.064237 [get_ports ethernet_1_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 1.25038 [get_ports ethernet_1_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 1.266237 [get_ports ethernet_1_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.130695 [get_ports ethernet_1_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.147259 [get_ports ethernet_1_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 1.246239 [get_ports ethernet_1_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 1.265732 [get_ports ethernet_1_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.059187 [get_ports ethernet_1_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.075751 [get_ports ethernet_1_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 1.23624 [get_ports ethernet_1_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 1.283104 [get_ports ethernet_1_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.034341 [get_ports ethernet_1_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.082821 [get_ports ethernet_1_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 1.225534 [get_ports ethernet_1_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 1.25644 [get_ports ethernet_1_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.019797 [get_ports ethernet_1_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.059995 [get_ports ethernet_1_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 1.258258 [get_ports ethernet_1_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 1.273913 [get_ports ethernet_1_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.136856 [get_ports ethernet_1_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.150794 [get_ports ethernet_1_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.121705 [get_ports ethernet_1_quad0_emac_pause_on[8]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.146753 [get_ports ethernet_1_quad0_emac_pause_on[8]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.146248 [get_ports ethernet_1_quad0_emac_pause_on[9]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.164125 [get_ports ethernet_1_quad0_emac_pause_on[9]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.119483 [get_ports ethernet_1_quad0_emac_pause_on[10]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.14342 [get_ports ethernet_1_quad0_emac_pause_on[10]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.106757 [get_ports ethernet_1_quad0_emac_pause_on[11]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.130189 [get_ports ethernet_1_quad0_emac_pause_on[11]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.114736 [get_ports ethernet_1_quad0_emac_pause_on[12]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.13837 [get_ports ethernet_1_quad0_emac_pause_on[12]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.119685 [get_ports ethernet_1_quad0_emac_pause_on[13]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.142915 [get_ports ethernet_1_quad0_emac_pause_on[13]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.128169 [get_ports ethernet_1_quad0_emac_pause_on[14]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.155439 [get_ports ethernet_1_quad0_emac_pause_on[14]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.14443 [get_ports ethernet_1_quad0_emac_pause_on[15]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.165337 [get_ports ethernet_1_quad0_emac_pause_on[15]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.198869 [get_ports ethernet_1_quad0_emac_pause_on[16]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.202909 [get_ports ethernet_1_quad0_emac_pause_on[16]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.194223 [get_ports ethernet_1_quad0_emac_pause_on[17]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.197354 [get_ports ethernet_1_quad0_emac_pause_on[17]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.183719 [get_ports ethernet_1_quad0_emac_pause_on[18]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.195738 [get_ports ethernet_1_quad0_emac_pause_on[18]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.247753 [get_ports ethernet_1_quad0_emac_pause_on[19]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.255833 [get_ports ethernet_1_quad0_emac_pause_on[19]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.192708 [get_ports ethernet_1_quad0_emac_pause_on[20]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.208969 [get_ports ethernet_1_quad0_emac_pause_on[20]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.245632 [get_ports ethernet_1_quad0_emac_pause_on[21]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.265731 [get_ports ethernet_1_quad0_emac_pause_on[21]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.174225 [get_ports ethernet_1_quad0_emac_pause_on[22]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.188769 [get_ports ethernet_1_quad0_emac_pause_on[22]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.209777 [get_ports ethernet_1_quad0_emac_pause_on[23]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.211494 [get_ports ethernet_1_quad0_emac_pause_on[23]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.202606 [get_ports ethernet_1_quad0_emac_pause_on[24]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.216847 [get_ports ethernet_1_quad0_emac_pause_on[24]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.211393 [get_ports ethernet_1_quad0_emac_pause_on[25]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.216746 [get_ports ethernet_1_quad0_emac_pause_on[25]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.203919 [get_ports ethernet_1_quad0_emac_pause_on[26]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.209777 [get_ports ethernet_1_quad0_emac_pause_on[26]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.211494 [get_ports ethernet_1_quad0_emac_pause_on[27]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.214726 [get_ports ethernet_1_quad0_emac_pause_on[27]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.191092 [get_ports ethernet_1_quad0_emac_pause_on[28]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.21816 [get_ports ethernet_1_quad0_emac_pause_on[28]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.215938 [get_ports ethernet_1_quad0_emac_pause_on[29]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.240683 [get_ports ethernet_1_quad0_emac_pause_on[29]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.20806 [get_ports ethernet_1_quad0_emac_pause_on[30]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.234118 [get_ports ethernet_1_quad0_emac_pause_on[30]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.189375 [get_ports ethernet_1_quad0_emac_pause_on[31]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.200586 [get_ports ethernet_1_quad0_emac_pause_on[31]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.348753 [get_ports ethernet_1_quad0_emac_xoff_gen[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.368448 [get_ports ethernet_1_quad0_emac_xoff_gen[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.311282 [get_ports ethernet_1_quad0_emac_xoff_gen[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.339966 [get_ports ethernet_1_quad0_emac_xoff_gen[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.330876 [get_ports ethernet_1_quad0_emac_xoff_gen[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.352995 [get_ports ethernet_1_quad0_emac_xoff_gen[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.321382 [get_ports ethernet_1_quad0_emac_xoff_gen[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.336027 [get_ports ethernet_1_quad0_emac_xoff_gen[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.340875 [get_ports ethernet_1_quad0_emac_xoff_gen[4]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.360974 [get_ports ethernet_1_quad0_emac_xoff_gen[4]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.371983 [get_ports ethernet_1_quad0_emac_xoff_gen[5]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.380467 [get_ports ethernet_1_quad0_emac_xoff_gen[5]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.330573 [get_ports ethernet_1_quad0_emac_xoff_gen[6]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.347238 [get_ports ethernet_1_quad0_emac_xoff_gen[6]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.281992 [get_ports ethernet_1_quad0_emac_xoff_gen[7]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.310878 [get_ports ethernet_1_quad0_emac_xoff_gen[7]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.126856 [get_ports ethernet_1_quad0_emac_xoff_gen[8]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.139885 [get_ports ethernet_1_quad0_emac_xoff_gen[8]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.121705 [get_ports ethernet_1_quad0_emac_xoff_gen[9]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.135542 [get_ports ethernet_1_quad0_emac_xoff_gen[9]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.121806 [get_ports ethernet_1_quad0_emac_xoff_gen[10]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.133724 [get_ports ethernet_1_quad0_emac_xoff_gen[10]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.129482 [get_ports ethernet_1_quad0_emac_xoff_gen[11]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.144531 [get_ports ethernet_1_quad0_emac_xoff_gen[11]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.108676 [get_ports ethernet_1_quad0_emac_xoff_gen[12]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.128068 [get_ports ethernet_1_quad0_emac_xoff_gen[12]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.14241 [get_ports ethernet_1_quad0_emac_xoff_gen[13]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.15958 [get_ports ethernet_1_quad0_emac_xoff_gen[13]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.135037 [get_ports ethernet_1_quad0_emac_xoff_gen[14]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.147359 [get_ports ethernet_1_quad0_emac_xoff_gen[14]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.10706 [get_ports ethernet_1_quad0_emac_xoff_gen[15]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.119584 [get_ports ethernet_1_quad0_emac_xoff_gen[15]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.135643 [get_ports ethernet_1_quad0_emac_xoff_gen[16]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.15251 [get_ports ethernet_1_quad0_emac_xoff_gen[16]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.160691 [get_ports ethernet_1_quad0_emac_xoff_gen[17]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.176952 [get_ports ethernet_1_quad0_emac_xoff_gen[17]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.14746 [get_ports ethernet_1_quad0_emac_xoff_gen[18]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.161499 [get_ports ethernet_1_quad0_emac_xoff_gen[18]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.152005 [get_ports ethernet_1_quad0_emac_xoff_gen[19]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.166347 [get_ports ethernet_1_quad0_emac_xoff_gen[19]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.153722 [get_ports ethernet_1_quad0_emac_xoff_gen[20]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.172306 [get_ports ethernet_1_quad0_emac_xoff_gen[20]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.148066 [get_ports ethernet_1_quad0_emac_xoff_gen[21]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.158166 [get_ports ethernet_1_quad0_emac_xoff_gen[21]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.14443 [get_ports ethernet_1_quad0_emac_xoff_gen[22]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.158065 [get_ports ethernet_1_quad0_emac_xoff_gen[22]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.140794 [get_ports ethernet_1_quad0_emac_xoff_gen[23]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.158267 [get_ports ethernet_1_quad0_emac_xoff_gen[23]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.164125 [get_ports ethernet_1_quad0_emac_xoff_gen[24]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.175538 [get_ports ethernet_1_quad0_emac_xoff_gen[24]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.136249 [get_ports ethernet_1_quad0_emac_xoff_gen[25]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.149682 [get_ports ethernet_1_quad0_emac_xoff_gen[25]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.12726 [get_ports ethernet_1_quad0_emac_xoff_gen[26]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.140996 [get_ports ethernet_1_quad0_emac_xoff_gen[26]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.136249 [get_ports ethernet_1_quad0_emac_xoff_gen[27]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.1515 [get_ports ethernet_1_quad0_emac_xoff_gen[27]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.137764 [get_ports ethernet_1_quad0_emac_xoff_gen[28]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.14948 [get_ports ethernet_1_quad0_emac_xoff_gen[28]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.153722 [get_ports ethernet_1_quad0_emac_xoff_gen[29]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.167963 [get_ports ethernet_1_quad0_emac_xoff_gen[29]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.149076 [get_ports ethernet_1_quad0_emac_xoff_gen[30]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.160186 [get_ports ethernet_1_quad0_emac_xoff_gen[30]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.134229 [get_ports ethernet_1_quad0_emac_xoff_gen[31]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.147561 [get_ports ethernet_1_quad0_emac_xoff_gen[31]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.255126 [get_ports ethernet_1_quad0_lpi_txhold[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.271286 [get_ports ethernet_1_quad0_lpi_txhold[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.120897 [get_ports ethernet_1_quad0_lpi_txhold[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.133825 [get_ports ethernet_1_quad0_lpi_txhold[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.164832 [get_ports ethernet_1_quad0_lpi_txhold[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.182002 [get_ports ethernet_1_quad0_lpi_txhold[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.115746 [get_ports ethernet_1_quad0_lpi_txhold[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.131603 [get_ports ethernet_1_quad0_lpi_txhold[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay -0.561863 [get_ports ethernet_1_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay -0.554894 [get_ports ethernet_1_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay -0.601152 [get_ports ethernet_1_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay -0.585093 [get_ports ethernet_1_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay -0.61509 [get_ports ethernet_1_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay -0.60196 [get_ports ethernet_1_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay -0.595597 [get_ports ethernet_1_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay -0.575397 [get_ports ethernet_1_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay -0.598122 [get_ports ethernet_1_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay -0.595597 [get_ports ethernet_1_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay -0.62519 [get_ports ethernet_1_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay -0.61408 [get_ports ethernet_1_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay -0.634482 [get_ports ethernet_1_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay -0.626301 [get_ports ethernet_1_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay -0.638825 [get_ports ethernet_1_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay -0.622463 [get_ports ethernet_1_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.207555 [get_ports ethernet_1_quad0_tx_hold_req[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.205636 [get_ports ethernet_1_quad0_tx_hold_req[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.100798 [get_ports ethernet_1_quad0_tx_hold_req[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.113322 [get_ports ethernet_1_quad0_tx_hold_req[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.162408 [get_ports ethernet_1_quad0_tx_hold_req[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.172811 [get_ports ethernet_1_quad0_tx_hold_req[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.117766 [get_ports ethernet_1_quad0_tx_hold_req[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.133825 [get_ports ethernet_1_quad0_tx_hold_req[3]]
# Quad MAC 0 Status
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.247956 [get_ports ethernet_1_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.275529 [get_ports ethernet_1_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.285023 [get_ports ethernet_1_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.298254 [get_ports ethernet_1_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.284215 [get_ports ethernet_1_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.297951 [get_ports ethernet_1_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.28169 [get_ports ethernet_1_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.290376 [get_ports ethernet_1_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 1.195436 [get_ports ethernet_1_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 1.222605 [get_ports ethernet_1_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 1.235836 [get_ports ethernet_1_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 1.249168 [get_ports ethernet_1_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 1.229271 [get_ports ethernet_1_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 1.244118 [get_ports ethernet_1_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 1.220181 [get_ports ethernet_1_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 1.232806 [get_ports ethernet_1_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.246037 [get_ports ethernet_1_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.270883 [get_ports ethernet_1_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.224524 [get_ports ethernet_1_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.237452 [get_ports ethernet_1_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.245835 [get_ports ethernet_1_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.272701 [get_ports ethernet_1_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.249673 [get_ports ethernet_1_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.260379 [get_ports ethernet_1_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 1.192911 [get_ports ethernet_1_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 1.218969 [get_ports ethernet_1_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 1.176044 [get_ports ethernet_1_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 1.189477 [get_ports ethernet_1_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 1.197355 [get_ports ethernet_1_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 1.223817 [get_ports ethernet_1_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 1.199779 [get_ports ethernet_1_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 1.21099 [get_ports ethernet_1_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 1.180791 [get_ports ethernet_1_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 1.181195 [get_ports ethernet_1_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 1.166752 [get_ports ethernet_1_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 1.189174 [get_ports ethernet_1_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 1.25341 [get_ports ethernet_1_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 1.256238 [get_ports ethernet_1_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 1.152713 [get_ports ethernet_1_m0_mac_tx_underflow[3]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 1.174832 [get_ports ethernet_1_m0_mac_tx_underflow[3]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay 1.153925 [get_ports ethernet_1_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay 1.157056 [get_ports ethernet_1_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay 1.132614 [get_ports ethernet_1_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay 1.154733 [get_ports ethernet_1_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay 1.222908 [get_ports ethernet_1_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay 1.226847 [get_ports ethernet_1_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay 1.118676 [get_ports ethernet_1_m0_mac_tx_underflow[3]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay 1.142916 [get_ports ethernet_1_m0_mac_tx_underflow[3]]
# Boundary pin delays for noc
# Boundary pin delays for pll_ddr
# Boundary pin delays for pll_eth_sys_ne_0
# Boundary pin delays for pll_eth_usr_ne_3
# Boundary pin delays for pll_gddr_SE
# Boundary pin delays for pll_gddr_SW
# Boundary pin delays for pll_noc_ne_1
# Boundary pin delays for pll_pcie
# Boundary pin delays for vp_clkio_ne
# Boundary pin delays for vp_clkio_nw
# Boundary pin delays for vp_clkio_se
# Boundary pin delays for vp_clkio_sw
# Boundary pin delays for vp_gpio_n_b0
# Core Data
# Boundary pin delays for vp_gpio_n_b1
# Core Data
# Boundary pin delays for vp_gpio_n_b2
# Core Data
# Boundary pin delays for vp_gpio_s_b0
# Core Data
# Boundary pin delays for vp_gpio_s_b1
# Core Clock
set_clock_latency -source -late -rise 0.2186751 [get_clocks mcio_vio_45_10_clk]
set_clock_latency -source -early -rise 0.20262418 [get_clocks mcio_vio_45_10_clk]
# Core Data
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay 1.147764 [get_ports mcio_vio_in[0]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay 1.147562 [get_ports mcio_vio_in[0]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay 0.972428 [get_ports mcio_vio_in[0]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay 0.988992 [get_ports mcio_vio_in[0]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay 1.105748 [get_ports mcio_vio_in[1]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay 1.116353 [get_ports mcio_vio_in[1]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay 0.995456 [get_ports mcio_vio_in[1]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay 1.012121 [get_ports mcio_vio_in[1]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay 1.098274 [get_ports mcio_vio_in[2]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay 1.106859 [get_ports mcio_vio_in[2]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay 0.977882 [get_ports mcio_vio_in[2]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay 0.994547 [get_ports mcio_vio_in[2]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay 1.157763 [get_ports mcio_vio_in[3]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay 1.152006 [get_ports mcio_vio_in[3]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay 0.979195 [get_ports mcio_vio_in[3]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay 0.997678 [get_ports mcio_vio_in[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.462378 [get_ports mcio_dir[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.451369 [get_ports mcio_dir[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.511262 [get_ports mcio_dir[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.502071 [get_ports mcio_dir[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.469145 [get_ports mcio_dir[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.444501 [get_ports mcio_dir[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.527018 [get_ports mcio_dir[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.505202 [get_ports mcio_dir[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.471468 [get_ports mcio_dir[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.442683 [get_ports mcio_dir[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.520049 [get_ports mcio_dir[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.495304 [get_ports mcio_dir[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.46965 [get_ports mcio_dir[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.442885 [get_ports mcio_dir[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.516211 [get_ports mcio_dir[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.493486 [get_ports mcio_dir[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.45955 [get_ports mcio_dir_45]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.439956 [get_ports mcio_dir_45]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.518231 [get_ports mcio_dir_45]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.499142 [get_ports mcio_dir_45]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.510151 [get_ports mcio_dir_45_oe]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.492375 [get_ports mcio_dir_45_oe]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.557217 [get_ports mcio_dir_45_oe]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.544087 [get_ports mcio_dir_45_oe]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.489345 [get_ports mcio_dir_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.470155 [get_ports mcio_dir_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.556106 [get_ports mcio_dir_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.538835 [get_ports mcio_dir_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.444905 [get_ports mcio_dir_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.42622 [get_ports mcio_dir_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.492981 [get_ports mcio_dir_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.479043 [get_ports mcio_dir_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.471165 [get_ports mcio_dir_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.447935 [get_ports mcio_dir_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.53328 [get_ports mcio_dir_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.512878 [get_ports mcio_dir_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.515605 [get_ports mcio_dir_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.492981 [get_ports mcio_dir_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.570448 [get_ports mcio_dir_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.552975 [get_ports mcio_dir_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.432179 [get_ports mcio_vio_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.410363 [get_ports mcio_vio_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.482881 [get_ports mcio_vio_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.464398 [get_ports mcio_vio_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.458641 [get_ports mcio_vio_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.440259 [get_ports mcio_vio_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.517625 [get_ports mcio_vio_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.500051 [get_ports mcio_vio_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.457732 [get_ports mcio_vio_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.427331 [get_ports mcio_vio_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.503687 [get_ports mcio_vio_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.47773 [get_ports mcio_vio_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.531058 [get_ports mcio_vio_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.508131 [get_ports mcio_vio_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.59186 [get_ports mcio_vio_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.572973 [get_ports mcio_vio_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.478437 [get_ports mcio_vio_out[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.453591 [get_ports mcio_vio_out[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.530149 [get_ports mcio_vio_out[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.508434 [get_ports mcio_vio_out[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.482679 [get_ports mcio_vio_out[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.458136 [get_ports mcio_vio_out[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.536714 [get_ports mcio_vio_out[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.51409 [get_ports mcio_vio_out[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.478538 [get_ports mcio_vio_out[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.451975 [get_ports mcio_vio_out[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.528634 [get_ports mcio_vio_out[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.505404 [get_ports mcio_vio_out[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.467125 [get_ports mcio_vio_out[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.445612 [get_ports mcio_vio_out[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.524594 [get_ports mcio_vio_out[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.505303 [get_ports mcio_vio_out[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.459045 [get_ports test[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.437936 [get_ports test[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.500859 [get_ports test[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.482477 [get_ports test[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.445814 [get_ports test_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.41612 [get_ports test_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.50399 [get_ports test_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.477326 [get_ports test_oe[2]]
# Boundary pin delays for vp_gpio_s_b2
# Core Data
# Boundary pin delays for vp_pll_nw_2
# Boundary pin delays for vp_pll_sw_2

######################################
# End IO Ring Boundary Delays SDC File
######################################
