#######################################
# ACE GENERATED DELAYS SDC FILE
# Generated on: 2023.06.12 at 14:46:13 PDT
# By: ACE 9.0.1
# From project: vp_project
#######################################
# IO Ring Boundary Delays SDC File
#######################################
# SDC PVT Conditions:
# Voltage: 850 Temperature: 125 Corner: slow
#######################################
# Boundary pin delays for ethernet_0
# Clocks and Resets
set_clock_latency -source -late -rise 0.852065 [get_clocks ethernet_0_m0_ff_clk_divby2]
set_clock_latency -source -early -rise 0.750781 [get_clocks ethernet_0_m0_ff_clk_divby2]
set_clock_latency -source -late -rise 0.931547 [get_clocks ethernet_0_m1_ff_clk_divby2]
set_clock_latency -source -early -rise 0.829754 [get_clocks ethernet_0_m1_ff_clk_divby2]
set_clock_latency -source -late -rise 0.822079 [get_clocks ethernet_0_ref_clk_divby2]
set_clock_latency -source -early -rise 0.768848 [get_clocks ethernet_0_ref_clk_divby2]
# Quad MAC 0 Flow Control
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 2.3123 [get_ports ethernet_0_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 2.3931 [get_ports ethernet_0_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.9448 [get_ports ethernet_0_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.0216 [get_ports ethernet_0_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 2.3842 [get_ports ethernet_0_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 2.5256 [get_ports ethernet_0_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.9946 [get_ports ethernet_0_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.1203 [get_ports ethernet_0_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 2.2582 [get_ports ethernet_0_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 2.3424 [get_ports ethernet_0_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.9271 [get_ports ethernet_0_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.0045 [get_ports ethernet_0_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 2.252 [get_ports ethernet_0_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 2.3302 [get_ports ethernet_0_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.0676 [get_ports ethernet_0_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.1481 [get_ports ethernet_0_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 2.244 [get_ports ethernet_0_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 2.3273 [get_ports ethernet_0_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.9321 [get_ports ethernet_0_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.012 [get_ports ethernet_0_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 2.1724 [get_ports ethernet_0_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 2.2377 [get_ports ethernet_0_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.8372 [get_ports ethernet_0_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 1.9071 [get_ports ethernet_0_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 2.1703 [get_ports ethernet_0_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 2.2343 [get_ports ethernet_0_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.8317 [get_ports ethernet_0_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 1.9073 [get_ports ethernet_0_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 2.256 [get_ports ethernet_0_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 2.3368 [get_ports ethernet_0_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.0655 [get_ports ethernet_0_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.1435 [get_ports ethernet_0_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.3667 [get_ports ethernet_0_quad0_emac_pause_on[8]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.478 [get_ports ethernet_0_quad0_emac_pause_on[8]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.2895 [get_ports ethernet_0_quad0_emac_pause_on[9]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.3443 [get_ports ethernet_0_quad0_emac_pause_on[9]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.2355 [get_ports ethernet_0_quad0_emac_pause_on[10]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.2945 [get_ports ethernet_0_quad0_emac_pause_on[10]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.2255 [get_ports ethernet_0_quad0_emac_pause_on[11]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.288 [get_ports ethernet_0_quad0_emac_pause_on[11]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.2437 [get_ports ethernet_0_quad0_emac_pause_on[12]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.3029 [get_ports ethernet_0_quad0_emac_pause_on[12]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.2687 [get_ports ethernet_0_quad0_emac_pause_on[13]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.3356 [get_ports ethernet_0_quad0_emac_pause_on[13]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.2807 [get_ports ethernet_0_quad0_emac_pause_on[14]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.3575 [get_ports ethernet_0_quad0_emac_pause_on[14]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.4083 [get_ports ethernet_0_quad0_emac_pause_on[15]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.5224 [get_ports ethernet_0_quad0_emac_pause_on[15]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.3713 [get_ports ethernet_0_quad0_emac_pause_on[16]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.4087 [get_ports ethernet_0_quad0_emac_pause_on[16]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.3507 [get_ports ethernet_0_quad0_emac_pause_on[17]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.3879 [get_ports ethernet_0_quad0_emac_pause_on[17]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.4179 [get_ports ethernet_0_quad0_emac_pause_on[18]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.4959 [get_ports ethernet_0_quad0_emac_pause_on[18]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.444 [get_ports ethernet_0_quad0_emac_pause_on[19]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.491 [get_ports ethernet_0_quad0_emac_pause_on[19]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.407 [get_ports ethernet_0_quad0_emac_pause_on[20]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.468 [get_ports ethernet_0_quad0_emac_pause_on[20]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.4893 [get_ports ethernet_0_quad0_emac_pause_on[21]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.5773 [get_ports ethernet_0_quad0_emac_pause_on[21]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.3218 [get_ports ethernet_0_quad0_emac_pause_on[22]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.365 [get_ports ethernet_0_quad0_emac_pause_on[22]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.4035 [get_ports ethernet_0_quad0_emac_pause_on[23]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.4568 [get_ports ethernet_0_quad0_emac_pause_on[23]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.3336 [get_ports ethernet_0_quad0_emac_pause_on[24]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.3656 [get_ports ethernet_0_quad0_emac_pause_on[24]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.4205 [get_ports ethernet_0_quad0_emac_pause_on[25]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.4737 [get_ports ethernet_0_quad0_emac_pause_on[25]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.4075 [get_ports ethernet_0_quad0_emac_pause_on[26]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.4584 [get_ports ethernet_0_quad0_emac_pause_on[26]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.3805 [get_ports ethernet_0_quad0_emac_pause_on[27]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.4113 [get_ports ethernet_0_quad0_emac_pause_on[27]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.3871 [get_ports ethernet_0_quad0_emac_pause_on[28]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.465 [get_ports ethernet_0_quad0_emac_pause_on[28]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.4016 [get_ports ethernet_0_quad0_emac_pause_on[29]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.4666 [get_ports ethernet_0_quad0_emac_pause_on[29]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.3445 [get_ports ethernet_0_quad0_emac_pause_on[30]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.3907 [get_ports ethernet_0_quad0_emac_pause_on[30]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.3757 [get_ports ethernet_0_quad0_emac_pause_on[31]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.4296 [get_ports ethernet_0_quad0_emac_pause_on[31]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.572 [get_ports ethernet_0_quad0_emac_xoff_gen[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.5989 [get_ports ethernet_0_quad0_emac_xoff_gen[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.5307 [get_ports ethernet_0_quad0_emac_xoff_gen[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.5726 [get_ports ethernet_0_quad0_emac_xoff_gen[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.5479 [get_ports ethernet_0_quad0_emac_xoff_gen[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.583 [get_ports ethernet_0_quad0_emac_xoff_gen[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.5235 [get_ports ethernet_0_quad0_emac_xoff_gen[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.5427 [get_ports ethernet_0_quad0_emac_xoff_gen[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.5535 [get_ports ethernet_0_quad0_emac_xoff_gen[4]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.5794 [get_ports ethernet_0_quad0_emac_xoff_gen[4]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.6944 [get_ports ethernet_0_quad0_emac_xoff_gen[5]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.7038 [get_ports ethernet_0_quad0_emac_xoff_gen[5]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.534 [get_ports ethernet_0_quad0_emac_xoff_gen[6]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.5574 [get_ports ethernet_0_quad0_emac_xoff_gen[6]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.4616 [get_ports ethernet_0_quad0_emac_xoff_gen[7]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.5034 [get_ports ethernet_0_quad0_emac_xoff_gen[7]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2261 [get_ports ethernet_0_quad0_emac_xoff_gen[8]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2396 [get_ports ethernet_0_quad0_emac_xoff_gen[8]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2058 [get_ports ethernet_0_quad0_emac_xoff_gen[9]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2262 [get_ports ethernet_0_quad0_emac_xoff_gen[9]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2208 [get_ports ethernet_0_quad0_emac_xoff_gen[10]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2328 [get_ports ethernet_0_quad0_emac_xoff_gen[10]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2324 [get_ports ethernet_0_quad0_emac_xoff_gen[11]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2529 [get_ports ethernet_0_quad0_emac_xoff_gen[11]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2559 [get_ports ethernet_0_quad0_emac_xoff_gen[12]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2821 [get_ports ethernet_0_quad0_emac_xoff_gen[12]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2591 [get_ports ethernet_0_quad0_emac_xoff_gen[13]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2819 [get_ports ethernet_0_quad0_emac_xoff_gen[13]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2317 [get_ports ethernet_0_quad0_emac_xoff_gen[14]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2482 [get_ports ethernet_0_quad0_emac_xoff_gen[14]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2119 [get_ports ethernet_0_quad0_emac_xoff_gen[15]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.225 [get_ports ethernet_0_quad0_emac_xoff_gen[15]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2379 [get_ports ethernet_0_quad0_emac_xoff_gen[16]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2665 [get_ports ethernet_0_quad0_emac_xoff_gen[16]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.3493 [get_ports ethernet_0_quad0_emac_xoff_gen[17]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.3729 [get_ports ethernet_0_quad0_emac_xoff_gen[17]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.3389 [get_ports ethernet_0_quad0_emac_xoff_gen[18]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.357 [get_ports ethernet_0_quad0_emac_xoff_gen[18]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.4502 [get_ports ethernet_0_quad0_emac_xoff_gen[19]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.4674 [get_ports ethernet_0_quad0_emac_xoff_gen[19]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.253 [get_ports ethernet_0_quad0_emac_xoff_gen[20]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2807 [get_ports ethernet_0_quad0_emac_xoff_gen[20]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.3475 [get_ports ethernet_0_quad0_emac_xoff_gen[21]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.3574 [get_ports ethernet_0_quad0_emac_xoff_gen[21]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2679 [get_ports ethernet_0_quad0_emac_xoff_gen[22]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2887 [get_ports ethernet_0_quad0_emac_xoff_gen[22]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2772 [get_ports ethernet_0_quad0_emac_xoff_gen[23]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.3 [get_ports ethernet_0_quad0_emac_xoff_gen[23]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.3556 [get_ports ethernet_0_quad0_emac_xoff_gen[24]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.3717 [get_ports ethernet_0_quad0_emac_xoff_gen[24]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2671 [get_ports ethernet_0_quad0_emac_xoff_gen[25]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2812 [get_ports ethernet_0_quad0_emac_xoff_gen[25]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2427 [get_ports ethernet_0_quad0_emac_xoff_gen[26]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2608 [get_ports ethernet_0_quad0_emac_xoff_gen[26]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2498 [get_ports ethernet_0_quad0_emac_xoff_gen[27]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.266 [get_ports ethernet_0_quad0_emac_xoff_gen[27]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2877 [get_ports ethernet_0_quad0_emac_xoff_gen[28]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.3058 [get_ports ethernet_0_quad0_emac_xoff_gen[28]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.3397 [get_ports ethernet_0_quad0_emac_xoff_gen[29]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.3552 [get_ports ethernet_0_quad0_emac_xoff_gen[29]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2726 [get_ports ethernet_0_quad0_emac_xoff_gen[30]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2874 [get_ports ethernet_0_quad0_emac_xoff_gen[30]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2411 [get_ports ethernet_0_quad0_emac_xoff_gen[31]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.258 [get_ports ethernet_0_quad0_emac_xoff_gen[31]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.4159 [get_ports ethernet_0_quad0_lpi_txhold[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.4327 [get_ports ethernet_0_quad0_lpi_txhold[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2865 [get_ports ethernet_0_quad0_lpi_txhold[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.3012 [get_ports ethernet_0_quad0_lpi_txhold[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.347 [get_ports ethernet_0_quad0_lpi_txhold[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.3727 [get_ports ethernet_0_quad0_lpi_txhold[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2617 [get_ports ethernet_0_quad0_lpi_txhold[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.28 [get_ports ethernet_0_quad0_lpi_txhold[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay -0.7365 [get_ports ethernet_0_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay -0.7341 [get_ports ethernet_0_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay -0.9104 [get_ports ethernet_0_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay -0.8877 [get_ports ethernet_0_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay -0.8758 [get_ports ethernet_0_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay -0.8639 [get_ports ethernet_0_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay -0.8444 [get_ports ethernet_0_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay -0.8153 [get_ports ethernet_0_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay -0.854 [get_ports ethernet_0_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay -0.8632 [get_ports ethernet_0_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay -0.9476 [get_ports ethernet_0_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay -0.9408 [get_ports ethernet_0_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay -0.931 [get_ports ethernet_0_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay -0.9325 [get_ports ethernet_0_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay -0.9487 [get_ports ethernet_0_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay -0.9348 [get_ports ethernet_0_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.411 [get_ports ethernet_0_quad0_tx_hold_req[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.4009 [get_ports ethernet_0_quad0_tx_hold_req[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.1884 [get_ports ethernet_0_quad0_tx_hold_req[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2003 [get_ports ethernet_0_quad0_tx_hold_req[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.3075 [get_ports ethernet_0_quad0_tx_hold_req[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.3213 [get_ports ethernet_0_quad0_tx_hold_req[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2458 [get_ports ethernet_0_quad0_tx_hold_req[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.266 [get_ports ethernet_0_quad0_tx_hold_req[3]]
# Quad MAC 0 Status
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.0428 [get_ports ethernet_0_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.1044 [get_ports ethernet_0_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.1417 [get_ports ethernet_0_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.1961 [get_ports ethernet_0_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.0937 [get_ports ethernet_0_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.1306 [get_ports ethernet_0_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.1021 [get_ports ethernet_0_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.1469 [get_ports ethernet_0_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 1.9755 [get_ports ethernet_0_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 2.0382 [get_ports ethernet_0_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 2.0627 [get_ports ethernet_0_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 2.1179 [get_ports ethernet_0_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 2.0257 [get_ports ethernet_0_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 2.063 [get_ports ethernet_0_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 2.0288 [get_ports ethernet_0_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 2.0744 [get_ports ethernet_0_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.0063 [get_ports ethernet_0_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.0475 [get_ports ethernet_0_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.0384 [get_ports ethernet_0_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.0901 [get_ports ethernet_0_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.0067 [get_ports ethernet_0_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.0552 [get_ports ethernet_0_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.063 [get_ports ethernet_0_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.1073 [get_ports ethernet_0_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 1.9434 [get_ports ethernet_0_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 1.9853 [get_ports ethernet_0_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 1.9518 [get_ports ethernet_0_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 2.0043 [get_ports ethernet_0_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 1.9505 [get_ports ethernet_0_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 1.9972 [get_ports ethernet_0_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 2.0025 [get_ports ethernet_0_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 2.0458 [get_ports ethernet_0_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 1.9767 [get_ports ethernet_0_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 2.0182 [get_ports ethernet_0_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 1.9783 [get_ports ethernet_0_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 2.0408 [get_ports ethernet_0_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 2.0596 [get_ports ethernet_0_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 2.0861 [get_ports ethernet_0_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 1.9177 [get_ports ethernet_0_m0_mac_tx_underflow[3]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 1.9524 [get_ports ethernet_0_m0_mac_tx_underflow[3]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay 1.9364 [get_ports ethernet_0_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay 1.9781 [get_ports ethernet_0_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay 1.9087 [get_ports ethernet_0_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay 1.9672 [get_ports ethernet_0_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay 2.006 [get_ports ethernet_0_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay 2.0354 [get_ports ethernet_0_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay 1.8657 [get_ports ethernet_0_m0_mac_tx_underflow[3]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay 1.903 [get_ports ethernet_0_m0_mac_tx_underflow[3]]
# Boundary pin delays for ethernet_1
# Clocks and Resets
set_clock_latency -source -late -rise 0.860136 [get_clocks ethernet_1_m0_ff_clk_divby2]
set_clock_latency -source -early -rise 0.739125 [get_clocks ethernet_1_m0_ff_clk_divby2]
set_clock_latency -source -late -rise 0.922209 [get_clocks ethernet_1_m1_ff_clk_divby2]
set_clock_latency -source -early -rise 0.816951 [get_clocks ethernet_1_m1_ff_clk_divby2]
set_clock_latency -source -late -rise 0.783763 [get_clocks ethernet_1_ref_clk_divby2]
set_clock_latency -source -early -rise 0.740783 [get_clocks ethernet_1_ref_clk_divby2]
# Quad MAC 0 Flow Control
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 2.2387 [get_ports ethernet_1_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 2.2863 [get_ports ethernet_1_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.8711 [get_ports ethernet_1_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.9147 [get_ports ethernet_1_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 2.1622 [get_ports ethernet_1_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 2.2162 [get_ports ethernet_1_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.7725 [get_ports ethernet_1_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.8107 [get_ports ethernet_1_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 2.1801 [get_ports ethernet_1_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 2.2271 [get_ports ethernet_1_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.849 [get_ports ethernet_1_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.8892 [get_ports ethernet_1_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 2.1641 [get_ports ethernet_1_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 2.2066 [get_ports ethernet_1_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.9797 [get_ports ethernet_1_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.0246 [get_ports ethernet_1_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 2.1752 [get_ports ethernet_1_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 2.2211 [get_ports ethernet_1_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.8634 [get_ports ethernet_1_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.9058 [get_ports ethernet_1_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 2.1555 [get_ports ethernet_1_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 2.2127 [get_ports ethernet_1_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.8203 [get_ports ethernet_1_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.882 [get_ports ethernet_1_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 2.1346 [get_ports ethernet_1_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 2.1796 [get_ports ethernet_1_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.7961 [get_ports ethernet_1_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.8526 [get_ports ethernet_1_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 2.1886 [get_ports ethernet_1_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 2.2393 [get_ports ethernet_1_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.998 [get_ports ethernet_1_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.0461 [get_ports ethernet_1_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.2017 [get_ports ethernet_1_quad0_emac_pause_on[8]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.2371 [get_ports ethernet_1_quad0_emac_pause_on[8]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.2311 [get_ports ethernet_1_quad0_emac_pause_on[9]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.2605 [get_ports ethernet_1_quad0_emac_pause_on[9]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.1936 [get_ports ethernet_1_quad0_emac_pause_on[10]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.228 [get_ports ethernet_1_quad0_emac_pause_on[10]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.1728 [get_ports ethernet_1_quad0_emac_pause_on[11]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.2072 [get_ports ethernet_1_quad0_emac_pause_on[11]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.1898 [get_ports ethernet_1_quad0_emac_pause_on[12]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.2233 [get_ports ethernet_1_quad0_emac_pause_on[12]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.1922 [get_ports ethernet_1_quad0_emac_pause_on[13]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.228 [get_ports ethernet_1_quad0_emac_pause_on[13]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.2165 [get_ports ethernet_1_quad0_emac_pause_on[14]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.2608 [get_ports ethernet_1_quad0_emac_pause_on[14]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.2347 [get_ports ethernet_1_quad0_emac_pause_on[15]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.2657 [get_ports ethernet_1_quad0_emac_pause_on[15]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.3077 [get_ports ethernet_1_quad0_emac_pause_on[16]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3164 [get_ports ethernet_1_quad0_emac_pause_on[16]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.2997 [get_ports ethernet_1_quad0_emac_pause_on[17]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3095 [get_ports ethernet_1_quad0_emac_pause_on[17]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.2911 [get_ports ethernet_1_quad0_emac_pause_on[18]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3094 [get_ports ethernet_1_quad0_emac_pause_on[18]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.3949 [get_ports ethernet_1_quad0_emac_pause_on[19]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.4158 [get_ports ethernet_1_quad0_emac_pause_on[19]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.3092 [get_ports ethernet_1_quad0_emac_pause_on[20]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3319 [get_ports ethernet_1_quad0_emac_pause_on[20]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.3989 [get_ports ethernet_1_quad0_emac_pause_on[21]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.4435 [get_ports ethernet_1_quad0_emac_pause_on[21]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.2754 [get_ports ethernet_1_quad0_emac_pause_on[22]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.2976 [get_ports ethernet_1_quad0_emac_pause_on[22]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.3257 [get_ports ethernet_1_quad0_emac_pause_on[23]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3278 [get_ports ethernet_1_quad0_emac_pause_on[23]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.321 [get_ports ethernet_1_quad0_emac_pause_on[24]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3469 [get_ports ethernet_1_quad0_emac_pause_on[24]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.3314 [get_ports ethernet_1_quad0_emac_pause_on[25]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3411 [get_ports ethernet_1_quad0_emac_pause_on[25]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.3148 [get_ports ethernet_1_quad0_emac_pause_on[26]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3257 [get_ports ethernet_1_quad0_emac_pause_on[26]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.3284 [get_ports ethernet_1_quad0_emac_pause_on[27]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3334 [get_ports ethernet_1_quad0_emac_pause_on[27]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.312 [get_ports ethernet_1_quad0_emac_pause_on[28]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3506 [get_ports ethernet_1_quad0_emac_pause_on[28]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.3516 [get_ports ethernet_1_quad0_emac_pause_on[29]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3884 [get_ports ethernet_1_quad0_emac_pause_on[29]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.3317 [get_ports ethernet_1_quad0_emac_pause_on[30]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3718 [get_ports ethernet_1_quad0_emac_pause_on[30]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.3052 [get_ports ethernet_1_quad0_emac_pause_on[31]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3216 [get_ports ethernet_1_quad0_emac_pause_on[31]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.5466 [get_ports ethernet_1_quad0_emac_xoff_gen[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.5738 [get_ports ethernet_1_quad0_emac_xoff_gen[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.488 [get_ports ethernet_1_quad0_emac_xoff_gen[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.531 [get_ports ethernet_1_quad0_emac_xoff_gen[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.5197 [get_ports ethernet_1_quad0_emac_xoff_gen[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.5555 [get_ports ethernet_1_quad0_emac_xoff_gen[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.509 [get_ports ethernet_1_quad0_emac_xoff_gen[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.5287 [get_ports ethernet_1_quad0_emac_xoff_gen[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.5346 [get_ports ethernet_1_quad0_emac_xoff_gen[4]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.561 [get_ports ethernet_1_quad0_emac_xoff_gen[4]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.5725 [get_ports ethernet_1_quad0_emac_xoff_gen[5]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.5845 [get_ports ethernet_1_quad0_emac_xoff_gen[5]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.5112 [get_ports ethernet_1_quad0_emac_xoff_gen[6]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.5353 [get_ports ethernet_1_quad0_emac_xoff_gen[6]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.4447 [get_ports ethernet_1_quad0_emac_xoff_gen[7]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.4869 [get_ports ethernet_1_quad0_emac_xoff_gen[7]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.202 [get_ports ethernet_1_quad0_emac_xoff_gen[8]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2162 [get_ports ethernet_1_quad0_emac_xoff_gen[8]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1916 [get_ports ethernet_1_quad0_emac_xoff_gen[9]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2122 [get_ports ethernet_1_quad0_emac_xoff_gen[9]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1986 [get_ports ethernet_1_quad0_emac_xoff_gen[10]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2114 [get_ports ethernet_1_quad0_emac_xoff_gen[10]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2144 [get_ports ethernet_1_quad0_emac_xoff_gen[11]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2352 [get_ports ethernet_1_quad0_emac_xoff_gen[11]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1795 [get_ports ethernet_1_quad0_emac_xoff_gen[12]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2073 [get_ports ethernet_1_quad0_emac_xoff_gen[12]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.232 [get_ports ethernet_1_quad0_emac_xoff_gen[13]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2555 [get_ports ethernet_1_quad0_emac_xoff_gen[13]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2075 [get_ports ethernet_1_quad0_emac_xoff_gen[14]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2248 [get_ports ethernet_1_quad0_emac_xoff_gen[14]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1786 [get_ports ethernet_1_quad0_emac_xoff_gen[15]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.1926 [get_ports ethernet_1_quad0_emac_xoff_gen[15]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2213 [get_ports ethernet_1_quad0_emac_xoff_gen[16]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2503 [get_ports ethernet_1_quad0_emac_xoff_gen[16]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2674 [get_ports ethernet_1_quad0_emac_xoff_gen[17]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2927 [get_ports ethernet_1_quad0_emac_xoff_gen[17]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2442 [get_ports ethernet_1_quad0_emac_xoff_gen[18]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2649 [get_ports ethernet_1_quad0_emac_xoff_gen[18]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2542 [get_ports ethernet_1_quad0_emac_xoff_gen[19]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2753 [get_ports ethernet_1_quad0_emac_xoff_gen[19]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2399 [get_ports ethernet_1_quad0_emac_xoff_gen[20]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2676 [get_ports ethernet_1_quad0_emac_xoff_gen[20]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2365 [get_ports ethernet_1_quad0_emac_xoff_gen[21]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2488 [get_ports ethernet_1_quad0_emac_xoff_gen[21]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2403 [get_ports ethernet_1_quad0_emac_xoff_gen[22]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2618 [get_ports ethernet_1_quad0_emac_xoff_gen[22]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2352 [get_ports ethernet_1_quad0_emac_xoff_gen[23]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.259 [get_ports ethernet_1_quad0_emac_xoff_gen[23]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2641 [get_ports ethernet_1_quad0_emac_xoff_gen[24]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.283 [get_ports ethernet_1_quad0_emac_xoff_gen[24]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2217 [get_ports ethernet_1_quad0_emac_xoff_gen[25]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2374 [get_ports ethernet_1_quad0_emac_xoff_gen[25]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2069 [get_ports ethernet_1_quad0_emac_xoff_gen[26]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2264 [get_ports ethernet_1_quad0_emac_xoff_gen[26]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2293 [get_ports ethernet_1_quad0_emac_xoff_gen[27]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2463 [get_ports ethernet_1_quad0_emac_xoff_gen[27]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2216 [get_ports ethernet_1_quad0_emac_xoff_gen[28]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2408 [get_ports ethernet_1_quad0_emac_xoff_gen[28]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2616 [get_ports ethernet_1_quad0_emac_xoff_gen[29]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2791 [get_ports ethernet_1_quad0_emac_xoff_gen[29]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2528 [get_ports ethernet_1_quad0_emac_xoff_gen[30]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2683 [get_ports ethernet_1_quad0_emac_xoff_gen[30]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2264 [get_ports ethernet_1_quad0_emac_xoff_gen[31]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2436 [get_ports ethernet_1_quad0_emac_xoff_gen[31]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.4007 [get_ports ethernet_1_quad0_lpi_txhold[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.4178 [get_ports ethernet_1_quad0_lpi_txhold[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1965 [get_ports ethernet_1_quad0_lpi_txhold[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2127 [get_ports ethernet_1_quad0_lpi_txhold[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2803 [get_ports ethernet_1_quad0_lpi_txhold[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.3076 [get_ports ethernet_1_quad0_lpi_txhold[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1878 [get_ports ethernet_1_quad0_lpi_txhold[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2081 [get_ports ethernet_1_quad0_lpi_txhold[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay -0.8824 [get_ports ethernet_1_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay -0.8771 [get_ports ethernet_1_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay -0.9386 [get_ports ethernet_1_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay -0.9149 [get_ports ethernet_1_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay -0.964 [get_ports ethernet_1_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay -0.9501 [get_ports ethernet_1_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay -0.9386 [get_ports ethernet_1_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay -0.9077 [get_ports ethernet_1_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay -0.9277 [get_ports ethernet_1_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay -0.934 [get_ports ethernet_1_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay -0.9684 [get_ports ethernet_1_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay -0.9608 [get_ports ethernet_1_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay -0.9886 [get_ports ethernet_1_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay -0.988 [get_ports ethernet_1_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay -0.9892 [get_ports ethernet_1_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay -0.9736 [get_ports ethernet_1_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.3251 [get_ports ethernet_1_quad0_tx_hold_req[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.3171 [get_ports ethernet_1_quad0_tx_hold_req[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1709 [get_ports ethernet_1_quad0_tx_hold_req[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.1832 [get_ports ethernet_1_quad0_tx_hold_req[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2687 [get_ports ethernet_1_quad0_tx_hold_req[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2836 [get_ports ethernet_1_quad0_tx_hold_req[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1977 [get_ports ethernet_1_quad0_tx_hold_req[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2193 [get_ports ethernet_1_quad0_tx_hold_req[3]]
# Quad MAC 0 Status
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 2.0099 [get_ports ethernet_1_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.0545 [get_ports ethernet_1_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 2.0865 [get_ports ethernet_1_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.114 [get_ports ethernet_1_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 2.0596 [get_ports ethernet_1_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.079 [get_ports ethernet_1_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 2.0664 [get_ports ethernet_1_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.0907 [get_ports ethernet_1_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 1.9442 [get_ports ethernet_1_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 1.9901 [get_ports ethernet_1_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 2.0276 [get_ports ethernet_1_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 2.0539 [get_ports ethernet_1_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 1.993 [get_ports ethernet_1_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 2.0134 [get_ports ethernet_1_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 1.9965 [get_ports ethernet_1_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 2.0218 [get_ports ethernet_1_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.993 [get_ports ethernet_1_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.0276 [get_ports ethernet_1_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.9774 [get_ports ethernet_1_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.9989 [get_ports ethernet_1_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.9951 [get_ports ethernet_1_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.0375 [get_ports ethernet_1_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 2.0286 [get_ports ethernet_1_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.0537 [get_ports ethernet_1_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 1.9303 [get_ports ethernet_1_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 1.9656 [get_ports ethernet_1_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 1.919 [get_ports ethernet_1_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 1.9412 [get_ports ethernet_1_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 1.9389 [get_ports ethernet_1_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 1.9796 [get_ports ethernet_1_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 1.9683 [get_ports ethernet_1_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 1.9928 [get_ports ethernet_1_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 1.9291 [get_ports ethernet_1_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 1.9425 [get_ports ethernet_1_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 1.9229 [get_ports ethernet_1_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 1.9578 [get_ports ethernet_1_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 2.0376 [get_ports ethernet_1_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 2.0562 [get_ports ethernet_1_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 1.9015 [get_ports ethernet_1_m0_mac_tx_underflow[3]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 1.9296 [get_ports ethernet_1_m0_mac_tx_underflow[3]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay 1.8903 [get_ports ethernet_1_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay 1.9054 [get_ports ethernet_1_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay 1.8763 [get_ports ethernet_1_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay 1.9065 [get_ports ethernet_1_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay 1.9955 [get_ports ethernet_1_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay 2.0148 [get_ports ethernet_1_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay 1.8509 [get_ports ethernet_1_m0_mac_tx_underflow[3]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay 1.8805 [get_ports ethernet_1_m0_mac_tx_underflow[3]]
# Boundary pin delays for noc
# Boundary pin delays for pll_ddr
# Boundary pin delays for pll_eth_sys_ne_0
# Boundary pin delays for pll_eth_usr_ne_3
# Boundary pin delays for pll_gddr_SE
# Boundary pin delays for pll_gddr_SW
# Boundary pin delays for pll_noc_ne_1
# Boundary pin delays for pll_pcie
# Boundary pin delays for vp_clkio_ne
# Boundary pin delays for vp_clkio_nw
# Boundary pin delays for vp_clkio_se
# Boundary pin delays for vp_clkio_sw
# Boundary pin delays for vp_gpio_n_b0
# Core Data
# Boundary pin delays for vp_gpio_n_b1
# Core Data
# Boundary pin delays for vp_gpio_n_b2
# Core Data
# Boundary pin delays for vp_gpio_s_b0
# Core Data
# Boundary pin delays for vp_gpio_s_b1
# Core Clock
set_clock_latency -source -late -rise 0.722933 [get_clocks mcio_vio_45_10_clk]
set_clock_latency -source -early -rise 0.647351 [get_clocks mcio_vio_45_10_clk]
# Core Data
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay 2.0109 [get_ports mcio_vio_in[0]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay 2.008 [get_ports mcio_vio_in[0]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay 1.7296 [get_ports mcio_vio_in[0]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay 1.7497 [get_ports mcio_vio_in[0]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay 1.9484 [get_ports mcio_vio_in[1]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay 1.9566 [get_ports mcio_vio_in[1]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay 1.7529 [get_ports mcio_vio_in[1]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay 1.7741 [get_ports mcio_vio_in[1]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay 1.9373 [get_ports mcio_vio_in[2]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay 1.9452 [get_ports mcio_vio_in[2]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay 1.7334 [get_ports mcio_vio_in[2]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay 1.7543 [get_ports mcio_vio_in[2]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay 2.0321 [get_ports mcio_vio_in[3]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay 2.0197 [get_ports mcio_vio_in[3]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay 1.7454 [get_ports mcio_vio_in[3]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay 1.7696 [get_ports mcio_vio_in[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.6999 [get_ports mcio_dir[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.6896 [get_ports mcio_dir[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.7628 [get_ports mcio_dir[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7623 [get_ports mcio_dir[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7101 [get_ports mcio_dir[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.6737 [get_ports mcio_dir[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.7797 [get_ports mcio_dir[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7558 [get_ports mcio_dir[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7185 [get_ports mcio_dir[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.679 [get_ports mcio_dir[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.7775 [get_ports mcio_dir[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7509 [get_ports mcio_dir[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7106 [get_ports mcio_dir[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.6743 [get_ports mcio_dir[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.7688 [get_ports mcio_dir[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7446 [get_ports mcio_dir[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.6954 [get_ports mcio_dir_45]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.6739 [get_ports mcio_dir_45]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.7669 [get_ports mcio_dir_45]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7536 [get_ports mcio_dir_45]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7735 [get_ports mcio_dir_45_oe]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.7519 [get_ports mcio_dir_45_oe]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.8328 [get_ports mcio_dir_45_oe]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.8231 [get_ports mcio_dir_45_oe]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7568 [get_ports mcio_dir_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.7331 [get_ports mcio_dir_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.834 [get_ports mcio_dir_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.8211 [get_ports mcio_dir_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.6828 [get_ports mcio_dir_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.6623 [get_ports mcio_dir_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.7417 [get_ports mcio_dir_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7345 [get_ports mcio_dir_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.717 [get_ports mcio_dir_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.6865 [get_ports mcio_dir_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.7877 [get_ports mcio_dir_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7691 [get_ports mcio_dir_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.8017 [get_ports mcio_dir_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.7764 [get_ports mcio_dir_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.8665 [get_ports mcio_dir_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.8538 [get_ports mcio_dir_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.6573 [get_ports mcio_vio_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.6336 [get_ports mcio_vio_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.7193 [get_ports mcio_vio_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7081 [get_ports mcio_vio_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.6906 [get_ports mcio_vio_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.6655 [get_ports mcio_vio_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.7597 [get_ports mcio_vio_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7456 [get_ports mcio_vio_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7031 [get_ports mcio_vio_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.668 [get_ports mcio_vio_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.7578 [get_ports mcio_vio_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7356 [get_ports mcio_vio_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.8006 [get_ports mcio_vio_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.7766 [get_ports mcio_vio_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.873 [get_ports mcio_vio_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.8609 [get_ports mcio_vio_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7182 [get_ports mcio_vio_out[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.6812 [get_ports mcio_vio_out[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.7794 [get_ports mcio_vio_out[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7552 [get_ports mcio_vio_out[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7228 [get_ports mcio_vio_out[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.6874 [get_ports mcio_vio_out[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.7898 [get_ports mcio_vio_out[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7648 [get_ports mcio_vio_out[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7271 [get_ports mcio_vio_out[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.6919 [get_ports mcio_vio_out[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.79 [get_ports mcio_vio_out[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.765 [get_ports mcio_vio_out[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7146 [get_ports mcio_vio_out[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.6797 [get_ports mcio_vio_out[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.7856 [get_ports mcio_vio_out[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7632 [get_ports mcio_vio_out[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7175 [get_ports test[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.6919 [get_ports test[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.7689 [get_ports test[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7531 [get_ports test[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.6841 [get_ports test_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.6479 [get_ports test_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.7534 [get_ports test_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7286 [get_ports test_oe[2]]
# Boundary pin delays for vp_gpio_s_b2
# Core Data
# Boundary pin delays for vp_pll_nw_2
# Boundary pin delays for vp_pll_sw_2

######################################
# End IO Ring Boundary Delays SDC File
######################################
