#######################################
# ACE GENERATED DELAYS SDC FILE
# Generated on: 2023.06.12 at 14:46:13 PDT
# By: ACE 9.0.1
# From project: vp_project
#######################################
# IO Ring Boundary Delays SDC File
#######################################
# SDC PVT Conditions:
# Voltage: 850 Temperature: 0 Corner: slow
#######################################
# Boundary pin delays for ethernet_0
# Clocks and Resets
set_clock_latency -source -late -rise 0.883344 [get_clocks ethernet_0_m0_ff_clk_divby2]
set_clock_latency -source -early -rise 0.794921 [get_clocks ethernet_0_m0_ff_clk_divby2]
set_clock_latency -source -late -rise 0.987256 [get_clocks ethernet_0_m1_ff_clk_divby2]
set_clock_latency -source -early -rise 0.891358 [get_clocks ethernet_0_m1_ff_clk_divby2]
set_clock_latency -source -late -rise 0.843528 [get_clocks ethernet_0_ref_clk_divby2]
set_clock_latency -source -early -rise 0.794441 [get_clocks ethernet_0_ref_clk_divby2]
# Quad MAC 0 Flow Control
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 2.470 [get_ports ethernet_0_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 2.5264 [get_ports ethernet_0_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.0666 [get_ports ethernet_0_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.1264 [get_ports ethernet_0_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 2.5344 [get_ports ethernet_0_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 2.6002 [get_ports ethernet_0_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.1025 [get_ports ethernet_0_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.162 [get_ports ethernet_0_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 2.4314 [get_ports ethernet_0_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 2.4839 [get_ports ethernet_0_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.0724 [get_ports ethernet_0_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.1185 [get_ports ethernet_0_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 2.4005 [get_ports ethernet_0_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 2.4539 [get_ports ethernet_0_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.2086 [get_ports ethernet_0_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.2590 [get_ports ethernet_0_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 2.441 [get_ports ethernet_0_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 2.4825 [get_ports ethernet_0_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.1004 [get_ports ethernet_0_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.1450 [get_ports ethernet_0_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 2.3417 [get_ports ethernet_0_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 2.4091 [get_ports ethernet_0_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.9779 [get_ports ethernet_0_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.0465 [get_ports ethernet_0_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 2.3605 [get_ports ethernet_0_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 2.4077 [get_ports ethernet_0_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 1.988 [get_ports ethernet_0_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.0502 [get_ports ethernet_0_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 2.4124 [get_ports ethernet_0_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 2.4607 [get_ports ethernet_0_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.206 [get_ports ethernet_0_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.2518 [get_ports ethernet_0_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.3291 [get_ports ethernet_0_quad0_emac_pause_on[8]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.4026 [get_ports ethernet_0_quad0_emac_pause_on[8]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.2735 [get_ports ethernet_0_quad0_emac_pause_on[9]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.3084 [get_ports ethernet_0_quad0_emac_pause_on[9]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.2223 [get_ports ethernet_0_quad0_emac_pause_on[10]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.2657 [get_ports ethernet_0_quad0_emac_pause_on[10]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.2132 [get_ports ethernet_0_quad0_emac_pause_on[11]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.2587 [get_ports ethernet_0_quad0_emac_pause_on[11]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.2295 [get_ports ethernet_0_quad0_emac_pause_on[12]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.2729 [get_ports ethernet_0_quad0_emac_pause_on[12]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.2439 [get_ports ethernet_0_quad0_emac_pause_on[13]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.2914 [get_ports ethernet_0_quad0_emac_pause_on[13]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.2644 [get_ports ethernet_0_quad0_emac_pause_on[14]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.3201 [get_ports ethernet_0_quad0_emac_pause_on[14]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.3670 [get_ports ethernet_0_quad0_emac_pause_on[15]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.4379 [get_ports ethernet_0_quad0_emac_pause_on[15]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.3571 [get_ports ethernet_0_quad0_emac_pause_on[16]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.3722 [get_ports ethernet_0_quad0_emac_pause_on[16]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.3471 [get_ports ethernet_0_quad0_emac_pause_on[17]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.3607 [get_ports ethernet_0_quad0_emac_pause_on[17]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.3974 [get_ports ethernet_0_quad0_emac_pause_on[18]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.4409 [get_ports ethernet_0_quad0_emac_pause_on[18]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.4649 [get_ports ethernet_0_quad0_emac_pause_on[19]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.4938 [get_ports ethernet_0_quad0_emac_pause_on[19]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.36 [get_ports ethernet_0_quad0_emac_pause_on[20]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.4045 [get_ports ethernet_0_quad0_emac_pause_on[20]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.4904 [get_ports ethernet_0_quad0_emac_pause_on[21]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.5449 [get_ports ethernet_0_quad0_emac_pause_on[21]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.2964 [get_ports ethernet_0_quad0_emac_pause_on[22]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.3278 [get_ports ethernet_0_quad0_emac_pause_on[22]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.4036 [get_ports ethernet_0_quad0_emac_pause_on[23]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.4236 [get_ports ethernet_0_quad0_emac_pause_on[23]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.3440 [get_ports ethernet_0_quad0_emac_pause_on[24]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.3665 [get_ports ethernet_0_quad0_emac_pause_on[24]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.4089 [get_ports ethernet_0_quad0_emac_pause_on[25]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.430 [get_ports ethernet_0_quad0_emac_pause_on[25]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.3794 [get_ports ethernet_0_quad0_emac_pause_on[26]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.4075 [get_ports ethernet_0_quad0_emac_pause_on[26]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.3667 [get_ports ethernet_0_quad0_emac_pause_on[27]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.3809 [get_ports ethernet_0_quad0_emac_pause_on[27]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.3783 [get_ports ethernet_0_quad0_emac_pause_on[28]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.4369 [get_ports ethernet_0_quad0_emac_pause_on[28]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.4024 [get_ports ethernet_0_quad0_emac_pause_on[29]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.4541 [get_ports ethernet_0_quad0_emac_pause_on[29]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.358 [get_ports ethernet_0_quad0_emac_pause_on[30]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.4024 [get_ports ethernet_0_quad0_emac_pause_on[30]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 0.3621 [get_ports ethernet_0_quad0_emac_pause_on[31]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 0.3923 [get_ports ethernet_0_quad0_emac_pause_on[31]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.5996 [get_ports ethernet_0_quad0_emac_xoff_gen[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.6238 [get_ports ethernet_0_quad0_emac_xoff_gen[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.5491 [get_ports ethernet_0_quad0_emac_xoff_gen[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.5931 [get_ports ethernet_0_quad0_emac_xoff_gen[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.5923 [get_ports ethernet_0_quad0_emac_xoff_gen[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.6217 [get_ports ethernet_0_quad0_emac_xoff_gen[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.5582 [get_ports ethernet_0_quad0_emac_xoff_gen[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.584 [get_ports ethernet_0_quad0_emac_xoff_gen[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.5859 [get_ports ethernet_0_quad0_emac_xoff_gen[4]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.6116 [get_ports ethernet_0_quad0_emac_xoff_gen[4]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.6806 [get_ports ethernet_0_quad0_emac_xoff_gen[5]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.7081 [get_ports ethernet_0_quad0_emac_xoff_gen[5]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.5521 [get_ports ethernet_0_quad0_emac_xoff_gen[6]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.5809 [get_ports ethernet_0_quad0_emac_xoff_gen[6]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.4849 [get_ports ethernet_0_quad0_emac_xoff_gen[7]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.5338 [get_ports ethernet_0_quad0_emac_xoff_gen[7]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2214 [get_ports ethernet_0_quad0_emac_xoff_gen[8]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2402 [get_ports ethernet_0_quad0_emac_xoff_gen[8]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2056 [get_ports ethernet_0_quad0_emac_xoff_gen[9]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2318 [get_ports ethernet_0_quad0_emac_xoff_gen[9]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.22 [get_ports ethernet_0_quad0_emac_xoff_gen[10]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.237 [get_ports ethernet_0_quad0_emac_xoff_gen[10]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2236 [get_ports ethernet_0_quad0_emac_xoff_gen[11]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2511 [get_ports ethernet_0_quad0_emac_xoff_gen[11]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2282 [get_ports ethernet_0_quad0_emac_xoff_gen[12]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2618 [get_ports ethernet_0_quad0_emac_xoff_gen[12]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2431 [get_ports ethernet_0_quad0_emac_xoff_gen[13]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.274 [get_ports ethernet_0_quad0_emac_xoff_gen[13]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2326 [get_ports ethernet_0_quad0_emac_xoff_gen[14]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2531 [get_ports ethernet_0_quad0_emac_xoff_gen[14]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.1955 [get_ports ethernet_0_quad0_emac_xoff_gen[15]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2169 [get_ports ethernet_0_quad0_emac_xoff_gen[15]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2442 [get_ports ethernet_0_quad0_emac_xoff_gen[16]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2738 [get_ports ethernet_0_quad0_emac_xoff_gen[16]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.3273 [get_ports ethernet_0_quad0_emac_xoff_gen[17]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.3574 [get_ports ethernet_0_quad0_emac_xoff_gen[17]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.3166 [get_ports ethernet_0_quad0_emac_xoff_gen[18]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.3432 [get_ports ethernet_0_quad0_emac_xoff_gen[18]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.3958 [get_ports ethernet_0_quad0_emac_xoff_gen[19]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.425 [get_ports ethernet_0_quad0_emac_xoff_gen[19]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2550 [get_ports ethernet_0_quad0_emac_xoff_gen[20]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2852 [get_ports ethernet_0_quad0_emac_xoff_gen[20]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.3199 [get_ports ethernet_0_quad0_emac_xoff_gen[21]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.3368 [get_ports ethernet_0_quad0_emac_xoff_gen[21]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2705 [get_ports ethernet_0_quad0_emac_xoff_gen[22]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2945 [get_ports ethernet_0_quad0_emac_xoff_gen[22]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2593 [get_ports ethernet_0_quad0_emac_xoff_gen[23]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2876 [get_ports ethernet_0_quad0_emac_xoff_gen[23]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.3351 [get_ports ethernet_0_quad0_emac_xoff_gen[24]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.3531 [get_ports ethernet_0_quad0_emac_xoff_gen[24]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2560 [get_ports ethernet_0_quad0_emac_xoff_gen[25]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2731 [get_ports ethernet_0_quad0_emac_xoff_gen[25]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2332 [get_ports ethernet_0_quad0_emac_xoff_gen[26]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2558 [get_ports ethernet_0_quad0_emac_xoff_gen[26]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2560 [get_ports ethernet_0_quad0_emac_xoff_gen[27]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.27 [get_ports ethernet_0_quad0_emac_xoff_gen[27]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2751 [get_ports ethernet_0_quad0_emac_xoff_gen[28]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2958 [get_ports ethernet_0_quad0_emac_xoff_gen[28]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.325 [get_ports ethernet_0_quad0_emac_xoff_gen[29]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.3492 [get_ports ethernet_0_quad0_emac_xoff_gen[29]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2735 [get_ports ethernet_0_quad0_emac_xoff_gen[30]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2918 [get_ports ethernet_0_quad0_emac_xoff_gen[30]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2428 [get_ports ethernet_0_quad0_emac_xoff_gen[31]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.260 [get_ports ethernet_0_quad0_emac_xoff_gen[31]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.4229 [get_ports ethernet_0_quad0_lpi_txhold[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.4436 [get_ports ethernet_0_quad0_lpi_txhold[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2577 [get_ports ethernet_0_quad0_lpi_txhold[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2807 [get_ports ethernet_0_quad0_lpi_txhold[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.3296 [get_ports ethernet_0_quad0_lpi_txhold[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.3615 [get_ports ethernet_0_quad0_lpi_txhold[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2395 [get_ports ethernet_0_quad0_lpi_txhold[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2655 [get_ports ethernet_0_quad0_lpi_txhold[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay -0.8764 [get_ports ethernet_0_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay -0.8647 [get_ports ethernet_0_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay -1.0131 [get_ports ethernet_0_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay -0.9890 [get_ports ethernet_0_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay -1.0052 [get_ports ethernet_0_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay -0.9835 [get_ports ethernet_0_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay -0.9720 [get_ports ethernet_0_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay -0.9382 [get_ports ethernet_0_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay -0.9687 [get_ports ethernet_0_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay -0.9727 [get_ports ethernet_0_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay -1.0492 [get_ports ethernet_0_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay -1.0439 [get_ports ethernet_0_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay -1.0500 [get_ports ethernet_0_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay -1.045 [get_ports ethernet_0_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay -1.053 [get_ports ethernet_0_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay -1.0372 [get_ports ethernet_0_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.4 [get_ports ethernet_0_quad0_tx_hold_req[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.3927 [get_ports ethernet_0_quad0_tx_hold_req[0]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.1763 [get_ports ethernet_0_quad0_tx_hold_req[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.1965 [get_ports ethernet_0_quad0_tx_hold_req[1]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.301 [get_ports ethernet_0_quad0_tx_hold_req[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.3176 [get_ports ethernet_0_quad0_tx_hold_req[2]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 0.2415 [get_ports ethernet_0_quad0_tx_hold_req[3]]
set_output_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 0.2628 [get_ports ethernet_0_quad0_tx_hold_req[3]]
# Quad MAC 0 Status
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.2116 [get_ports ethernet_0_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.2709 [get_ports ethernet_0_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.3278 [get_ports ethernet_0_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.3494 [get_ports ethernet_0_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.2808 [get_ports ethernet_0_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.2902 [get_ports ethernet_0_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.2955 [get_ports ethernet_0_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.3075 [get_ports ethernet_0_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 2.1352 [get_ports ethernet_0_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 2.1933 [get_ports ethernet_0_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 2.245 [get_ports ethernet_0_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 2.2669 [get_ports ethernet_0_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 2.2005 [get_ports ethernet_0_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 2.2117 [get_ports ethernet_0_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 2.2115 [get_ports ethernet_0_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 2.2263 [get_ports ethernet_0_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.1768 [get_ports ethernet_0_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.213 [get_ports ethernet_0_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.2135 [get_ports ethernet_0_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.2300 [get_ports ethernet_0_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.1833 [get_ports ethernet_0_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.2265 [get_ports ethernet_0_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -max -add_delay 2.2474 [get_ports ethernet_0_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -max -add_delay 2.2629 [get_ports ethernet_0_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 2.1036 [get_ports ethernet_0_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 2.140 [get_ports ethernet_0_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 2.1255 [get_ports ethernet_0_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 2.1437 [get_ports ethernet_0_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 2.1166 [get_ports ethernet_0_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 2.1573 [get_ports ethernet_0_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -rise -min -add_delay 2.177 [get_ports ethernet_0_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_M0_FF_CLK -fall -min -add_delay 2.1919 [get_ports ethernet_0_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 2.1558 [get_ports ethernet_0_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 2.1526 [get_ports ethernet_0_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 2.1385 [get_ports ethernet_0_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 2.1790 [get_ports ethernet_0_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 2.2571 [get_ports ethernet_0_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 2.2475 [get_ports ethernet_0_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -max -add_delay 2.0632 [get_ports ethernet_0_m0_mac_tx_underflow[3]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -max -add_delay 2.090 [get_ports ethernet_0_m0_mac_tx_underflow[3]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay 2.1101 [get_ports ethernet_0_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay 2.1101 [get_ports ethernet_0_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay 2.0714 [get_ports ethernet_0_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay 2.1083 [get_ports ethernet_0_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay 2.1995 [get_ports ethernet_0_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay 2.1930 [get_ports ethernet_0_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -rise -min -add_delay 2.0111 [get_ports ethernet_0_m0_mac_tx_underflow[3]]
set_input_delay -clock v_acx_sc_ETH_0_REF_CLK -fall -min -add_delay 2.0376 [get_ports ethernet_0_m0_mac_tx_underflow[3]]
# Boundary pin delays for ethernet_1
# Clocks and Resets
set_clock_latency -source -late -rise 0.893470 [get_clocks ethernet_1_m0_ff_clk_divby2]
set_clock_latency -source -early -rise 0.784471 [get_clocks ethernet_1_m0_ff_clk_divby2]
set_clock_latency -source -late -rise 0.981283 [get_clocks ethernet_1_m1_ff_clk_divby2]
set_clock_latency -source -early -rise 0.880674 [get_clocks ethernet_1_m1_ff_clk_divby2]
set_clock_latency -source -late -rise 0.815776 [get_clocks ethernet_1_ref_clk_divby2]
set_clock_latency -source -early -rise 0.773782 [get_clocks ethernet_1_ref_clk_divby2]
# Quad MAC 0 Flow Control
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 2.4148 [get_ports ethernet_1_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 2.4570 [get_ports ethernet_1_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 2.011 [get_ports ethernet_1_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.0570 [get_ports ethernet_1_quad0_emac_pause_on[0]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 2.3759 [get_ports ethernet_1_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 2.4000 [get_ports ethernet_1_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.9440 [get_ports ethernet_1_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 1.9620 [get_ports ethernet_1_quad0_emac_pause_on[1]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 2.3732 [get_ports ethernet_1_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 2.4101 [get_ports ethernet_1_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 2.0142 [get_ports ethernet_1_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.0445 [get_ports ethernet_1_quad0_emac_pause_on[2]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 2.3389 [get_ports ethernet_1_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 2.3762 [get_ports ethernet_1_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 2.1470 [get_ports ethernet_1_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.1814 [get_ports ethernet_1_quad0_emac_pause_on[3]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 2.3890 [get_ports ethernet_1_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 2.4145 [get_ports ethernet_1_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 2.0482 [get_ports ethernet_1_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.0771 [get_ports ethernet_1_quad0_emac_pause_on[4]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 2.3294 [get_ports ethernet_1_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 2.393 [get_ports ethernet_1_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.9656 [get_ports ethernet_1_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.03 [get_ports ethernet_1_quad0_emac_pause_on[5]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 2.3343 [get_ports ethernet_1_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 2.3732 [get_ports ethernet_1_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 1.9615 [get_ports ethernet_1_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.0157 [get_ports ethernet_1_quad0_emac_pause_on[6]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 2.3620 [get_ports ethernet_1_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 2.3982 [get_ports ethernet_1_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 2.1555 [get_ports ethernet_1_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.1895 [get_ports ethernet_1_quad0_emac_pause_on[7]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.1991 [get_ports ethernet_1_quad0_emac_pause_on[8]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.233 [get_ports ethernet_1_quad0_emac_pause_on[8]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.2334 [get_ports ethernet_1_quad0_emac_pause_on[9]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.2564 [get_ports ethernet_1_quad0_emac_pause_on[9]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.1905 [get_ports ethernet_1_quad0_emac_pause_on[10]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.2235 [get_ports ethernet_1_quad0_emac_pause_on[10]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.1741 [get_ports ethernet_1_quad0_emac_pause_on[11]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.2072 [get_ports ethernet_1_quad0_emac_pause_on[11]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.1893 [get_ports ethernet_1_quad0_emac_pause_on[12]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.2220 [get_ports ethernet_1_quad0_emac_pause_on[12]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.1883 [get_ports ethernet_1_quad0_emac_pause_on[13]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.2218 [get_ports ethernet_1_quad0_emac_pause_on[13]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.2145 [get_ports ethernet_1_quad0_emac_pause_on[14]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.2572 [get_ports ethernet_1_quad0_emac_pause_on[14]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.2342 [get_ports ethernet_1_quad0_emac_pause_on[15]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.2630 [get_ports ethernet_1_quad0_emac_pause_on[15]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.3125 [get_ports ethernet_1_quad0_emac_pause_on[16]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3149 [get_ports ethernet_1_quad0_emac_pause_on[16]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.3097 [get_ports ethernet_1_quad0_emac_pause_on[17]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3113 [get_ports ethernet_1_quad0_emac_pause_on[17]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.3002 [get_ports ethernet_1_quad0_emac_pause_on[18]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3148 [get_ports ethernet_1_quad0_emac_pause_on[18]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.4289 [get_ports ethernet_1_quad0_emac_pause_on[19]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.4453 [get_ports ethernet_1_quad0_emac_pause_on[19]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.2940 [get_ports ethernet_1_quad0_emac_pause_on[20]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3168 [get_ports ethernet_1_quad0_emac_pause_on[20]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.4229 [get_ports ethernet_1_quad0_emac_pause_on[21]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.459 [get_ports ethernet_1_quad0_emac_pause_on[21]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.2668 [get_ports ethernet_1_quad0_emac_pause_on[22]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.289 [get_ports ethernet_1_quad0_emac_pause_on[22]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.3440 [get_ports ethernet_1_quad0_emac_pause_on[23]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3378 [get_ports ethernet_1_quad0_emac_pause_on[23]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.3364 [get_ports ethernet_1_quad0_emac_pause_on[24]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3553 [get_ports ethernet_1_quad0_emac_pause_on[24]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.3421 [get_ports ethernet_1_quad0_emac_pause_on[25]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3443 [get_ports ethernet_1_quad0_emac_pause_on[25]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.3124 [get_ports ethernet_1_quad0_emac_pause_on[26]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3204 [get_ports ethernet_1_quad0_emac_pause_on[26]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.3279 [get_ports ethernet_1_quad0_emac_pause_on[27]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3315 [get_ports ethernet_1_quad0_emac_pause_on[27]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.32 [get_ports ethernet_1_quad0_emac_pause_on[28]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3644 [get_ports ethernet_1_quad0_emac_pause_on[28]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.3652 [get_ports ethernet_1_quad0_emac_pause_on[29]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.4047 [get_ports ethernet_1_quad0_emac_pause_on[29]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.3497 [get_ports ethernet_1_quad0_emac_pause_on[30]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3908 [get_ports ethernet_1_quad0_emac_pause_on[30]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 0.3092 [get_ports ethernet_1_quad0_emac_pause_on[31]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 0.3224 [get_ports ethernet_1_quad0_emac_pause_on[31]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.582 [get_ports ethernet_1_quad0_emac_xoff_gen[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.6057 [get_ports ethernet_1_quad0_emac_xoff_gen[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.5204 [get_ports ethernet_1_quad0_emac_xoff_gen[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.5641 [get_ports ethernet_1_quad0_emac_xoff_gen[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.571 [get_ports ethernet_1_quad0_emac_xoff_gen[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.6000 [get_ports ethernet_1_quad0_emac_xoff_gen[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.5508 [get_ports ethernet_1_quad0_emac_xoff_gen[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.5758 [get_ports ethernet_1_quad0_emac_xoff_gen[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.5735 [get_ports ethernet_1_quad0_emac_xoff_gen[4]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.5991 [get_ports ethernet_1_quad0_emac_xoff_gen[4]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.5933 [get_ports ethernet_1_quad0_emac_xoff_gen[5]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.6196 [get_ports ethernet_1_quad0_emac_xoff_gen[5]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.5351 [get_ports ethernet_1_quad0_emac_xoff_gen[6]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.5640 [get_ports ethernet_1_quad0_emac_xoff_gen[6]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.474 [get_ports ethernet_1_quad0_emac_xoff_gen[7]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.5214 [get_ports ethernet_1_quad0_emac_xoff_gen[7]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2037 [get_ports ethernet_1_quad0_emac_xoff_gen[8]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2227 [get_ports ethernet_1_quad0_emac_xoff_gen[8]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1958 [get_ports ethernet_1_quad0_emac_xoff_gen[9]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2214 [get_ports ethernet_1_quad0_emac_xoff_gen[9]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2052 [get_ports ethernet_1_quad0_emac_xoff_gen[10]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2206 [get_ports ethernet_1_quad0_emac_xoff_gen[10]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2118 [get_ports ethernet_1_quad0_emac_xoff_gen[11]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2389 [get_ports ethernet_1_quad0_emac_xoff_gen[11]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1761 [get_ports ethernet_1_quad0_emac_xoff_gen[12]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.209 [get_ports ethernet_1_quad0_emac_xoff_gen[12]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2245 [get_ports ethernet_1_quad0_emac_xoff_gen[13]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.255 [get_ports ethernet_1_quad0_emac_xoff_gen[13]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2154 [get_ports ethernet_1_quad0_emac_xoff_gen[14]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2364 [get_ports ethernet_1_quad0_emac_xoff_gen[14]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1749 [get_ports ethernet_1_quad0_emac_xoff_gen[15]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.1960 [get_ports ethernet_1_quad0_emac_xoff_gen[15]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2340 [get_ports ethernet_1_quad0_emac_xoff_gen[16]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2634 [get_ports ethernet_1_quad0_emac_xoff_gen[16]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2746 [get_ports ethernet_1_quad0_emac_xoff_gen[17]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.304 [get_ports ethernet_1_quad0_emac_xoff_gen[17]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2498 [get_ports ethernet_1_quad0_emac_xoff_gen[18]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2764 [get_ports ethernet_1_quad0_emac_xoff_gen[18]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2566 [get_ports ethernet_1_quad0_emac_xoff_gen[19]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2834 [get_ports ethernet_1_quad0_emac_xoff_gen[19]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2465 [get_ports ethernet_1_quad0_emac_xoff_gen[20]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2760 [get_ports ethernet_1_quad0_emac_xoff_gen[20]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2398 [get_ports ethernet_1_quad0_emac_xoff_gen[21]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2550 [get_ports ethernet_1_quad0_emac_xoff_gen[21]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2490 [get_ports ethernet_1_quad0_emac_xoff_gen[22]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2729 [get_ports ethernet_1_quad0_emac_xoff_gen[22]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2298 [get_ports ethernet_1_quad0_emac_xoff_gen[23]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2577 [get_ports ethernet_1_quad0_emac_xoff_gen[23]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2772 [get_ports ethernet_1_quad0_emac_xoff_gen[24]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2941 [get_ports ethernet_1_quad0_emac_xoff_gen[24]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2264 [get_ports ethernet_1_quad0_emac_xoff_gen[25]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.243 [get_ports ethernet_1_quad0_emac_xoff_gen[25]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2105 [get_ports ethernet_1_quad0_emac_xoff_gen[26]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2325 [get_ports ethernet_1_quad0_emac_xoff_gen[26]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2412 [get_ports ethernet_1_quad0_emac_xoff_gen[27]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2579 [get_ports ethernet_1_quad0_emac_xoff_gen[27]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2334 [get_ports ethernet_1_quad0_emac_xoff_gen[28]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2533 [get_ports ethernet_1_quad0_emac_xoff_gen[28]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2721 [get_ports ethernet_1_quad0_emac_xoff_gen[29]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2958 [get_ports ethernet_1_quad0_emac_xoff_gen[29]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2589 [get_ports ethernet_1_quad0_emac_xoff_gen[30]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2768 [get_ports ethernet_1_quad0_emac_xoff_gen[30]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2334 [get_ports ethernet_1_quad0_emac_xoff_gen[31]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.249 [get_ports ethernet_1_quad0_emac_xoff_gen[31]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.4122 [get_ports ethernet_1_quad0_lpi_txhold[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.4328 [get_ports ethernet_1_quad0_lpi_txhold[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1973 [get_ports ethernet_1_quad0_lpi_txhold[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2188 [get_ports ethernet_1_quad0_lpi_txhold[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2850 [get_ports ethernet_1_quad0_lpi_txhold[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.3160 [get_ports ethernet_1_quad0_lpi_txhold[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1885 [get_ports ethernet_1_quad0_lpi_txhold[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.214 [get_ports ethernet_1_quad0_lpi_txhold[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay -0.9791 [get_ports ethernet_1_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay -0.9690 [get_ports ethernet_1_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay -1.0350 [get_ports ethernet_1_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay -1.0108 [get_ports ethernet_1_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay -1.0688 [get_ports ethernet_1_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay -1.0483 [get_ports ethernet_1_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay -1.0355 [get_ports ethernet_1_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay -1.0021 [get_ports ethernet_1_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay -1.0243 [get_ports ethernet_1_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay -1.0308 [get_ports ethernet_1_quad0_mac_stop_tx[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay -1.0654 [get_ports ethernet_1_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay -1.06 [get_ports ethernet_1_quad0_mac_stop_tx[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay -1.0943 [get_ports ethernet_1_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay -1.0913 [get_ports ethernet_1_quad0_mac_stop_tx[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay -1.0860 [get_ports ethernet_1_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay -1.0709 [get_ports ethernet_1_quad0_mac_stop_tx[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.3438 [get_ports ethernet_1_quad0_tx_hold_req[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.3327 [get_ports ethernet_1_quad0_tx_hold_req[0]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.1632 [get_ports ethernet_1_quad0_tx_hold_req[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.1834 [get_ports ethernet_1_quad0_tx_hold_req[1]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2732 [get_ports ethernet_1_quad0_tx_hold_req[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2894 [get_ports ethernet_1_quad0_tx_hold_req[2]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 0.2077 [get_ports ethernet_1_quad0_tx_hold_req[3]]
set_output_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 0.2288 [get_ports ethernet_1_quad0_tx_hold_req[3]]
# Quad MAC 0 Status
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 2.1873 [get_ports ethernet_1_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.2385 [get_ports ethernet_1_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 2.2868 [get_ports ethernet_1_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.2958 [get_ports ethernet_1_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 2.255 [get_ports ethernet_1_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.256 [get_ports ethernet_1_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 2.268 [get_ports ethernet_1_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.2711 [get_ports ethernet_1_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 2.1142 [get_ports ethernet_1_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 2.164 [get_ports ethernet_1_m0_ffe_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 2.2193 [get_ports ethernet_1_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 2.2279 [get_ports ethernet_1_m0_ffe_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 2.1785 [get_ports ethernet_1_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 2.1817 [get_ports ethernet_1_m0_ffe_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 2.1886 [get_ports ethernet_1_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 2.1943 [get_ports ethernet_1_m0_ffe_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 2.1657 [get_ports ethernet_1_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.1986 [get_ports ethernet_1_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 2.1667 [get_ports ethernet_1_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.1697 [get_ports ethernet_1_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 2.174 [get_ports ethernet_1_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.2136 [get_ports ethernet_1_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -max -add_delay 2.2214 [get_ports ethernet_1_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -max -add_delay 2.228 [get_ports ethernet_1_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 2.0951 [get_ports ethernet_1_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 2.1286 [get_ports ethernet_1_m0_ffp_tx_ovr[0]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 2.10 [get_ports ethernet_1_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 2.1049 [get_ports ethernet_1_m0_ffp_tx_ovr[1]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 2.1093 [get_ports ethernet_1_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 2.1471 [get_ports ethernet_1_m0_ffp_tx_ovr[2]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -rise -min -add_delay 2.1531 [get_ports ethernet_1_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_M0_FF_CLK -fall -min -add_delay 2.1600 [get_ports ethernet_1_m0_ffp_tx_ovr[3]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 2.1209 [get_ports ethernet_1_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 2.1043 [get_ports ethernet_1_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 2.0983 [get_ports ethernet_1_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 2.125 [get_ports ethernet_1_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 2.2406 [get_ports ethernet_1_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 2.2268 [get_ports ethernet_1_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -max -add_delay 2.0519 [get_ports ethernet_1_m0_mac_tx_underflow[3]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -max -add_delay 2.0746 [get_ports ethernet_1_m0_mac_tx_underflow[3]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay 2.0762 [get_ports ethernet_1_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay 2.0635 [get_ports ethernet_1_m0_mac_tx_underflow[0]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay 2.0464 [get_ports ethernet_1_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay 2.0704 [get_ports ethernet_1_m0_mac_tx_underflow[1]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay 2.1906 [get_ports ethernet_1_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay 2.180 [get_ports ethernet_1_m0_mac_tx_underflow[2]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -rise -min -add_delay 2.0001 [get_ports ethernet_1_m0_mac_tx_underflow[3]]
set_input_delay -clock v_acx_sc_ETH_1_REF_CLK -fall -min -add_delay 2.0227 [get_ports ethernet_1_m0_mac_tx_underflow[3]]
# Boundary pin delays for noc
# Boundary pin delays for pll_ddr
# Boundary pin delays for pll_eth_sys_ne_0
# Boundary pin delays for pll_eth_usr_ne_3
# Boundary pin delays for pll_gddr_SE
# Boundary pin delays for pll_gddr_SW
# Boundary pin delays for pll_noc_ne_1
# Boundary pin delays for pll_pcie
# Boundary pin delays for vp_clkio_ne
# Boundary pin delays for vp_clkio_nw
# Boundary pin delays for vp_clkio_se
# Boundary pin delays for vp_clkio_sw
# Boundary pin delays for vp_gpio_n_b0
# Core Data
# Boundary pin delays for vp_gpio_n_b1
# Core Data
# Boundary pin delays for vp_gpio_n_b2
# Core Data
# Boundary pin delays for vp_gpio_s_b0
# Core Data
# Boundary pin delays for vp_gpio_s_b1
# Core Clock
set_clock_latency -source -late -rise 0.740780 [get_clocks mcio_vio_45_10_clk]
set_clock_latency -source -early -rise 0.665719 [get_clocks mcio_vio_45_10_clk]
# Core Data
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay 2.1736 [get_ports mcio_vio_in[0]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay 2.1527 [get_ports mcio_vio_in[0]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay 1.8662 [get_ports mcio_vio_in[0]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay 1.8723 [get_ports mcio_vio_in[0]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay 2.083 [get_ports mcio_vio_in[1]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay 2.0866 [get_ports mcio_vio_in[1]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay 1.8884 [get_ports mcio_vio_in[1]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay 1.8995 [get_ports mcio_vio_in[1]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay 2.0854 [get_ports mcio_vio_in[2]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay 2.0799 [get_ports mcio_vio_in[2]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay 1.8788 [get_ports mcio_vio_in[2]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay 1.884 [get_ports mcio_vio_in[2]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay 2.2050 [get_ports mcio_vio_in[3]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay 2.1834 [get_ports mcio_vio_in[3]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay 1.8761 [get_ports mcio_vio_in[3]]
set_input_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay 1.8855 [get_ports mcio_vio_in[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7253 [get_ports mcio_dir[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.7081 [get_ports mcio_dir[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.795 [get_ports mcio_dir[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7907 [get_ports mcio_dir[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7432 [get_ports mcio_dir[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.7005 [get_ports mcio_dir[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.8146 [get_ports mcio_dir[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7902 [get_ports mcio_dir[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7532 [get_ports mcio_dir[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.7055 [get_ports mcio_dir[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.8166 [get_ports mcio_dir[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7870 [get_ports mcio_dir[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7480 [get_ports mcio_dir[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.7042 [get_ports mcio_dir[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.8093 [get_ports mcio_dir[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7831 [get_ports mcio_dir[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7293 [get_ports mcio_dir_45]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.6956 [get_ports mcio_dir_45]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.8026 [get_ports mcio_dir_45]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7819 [get_ports mcio_dir_45]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.8072 [get_ports mcio_dir_45_oe]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.7808 [get_ports mcio_dir_45_oe]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.870 [get_ports mcio_dir_45_oe]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.8612 [get_ports mcio_dir_45_oe]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.811 [get_ports mcio_dir_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.7835 [get_ports mcio_dir_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.8896 [get_ports mcio_dir_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.8783 [get_ports mcio_dir_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7172 [get_ports mcio_dir_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.6887 [get_ports mcio_dir_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.7803 [get_ports mcio_dir_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7709 [get_ports mcio_dir_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7647 [get_ports mcio_dir_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.7286 [get_ports mcio_dir_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.8369 [get_ports mcio_dir_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.819 [get_ports mcio_dir_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.8510 [get_ports mcio_dir_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.8142 [get_ports mcio_dir_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.9194 [get_ports mcio_dir_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.9010 [get_ports mcio_dir_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.6977 [get_ports mcio_vio_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.6695 [get_ports mcio_vio_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.762 [get_ports mcio_vio_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7523 [get_ports mcio_vio_oe[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7188 [get_ports mcio_vio_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.6885 [get_ports mcio_vio_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.7953 [get_ports mcio_vio_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.776 [get_ports mcio_vio_oe[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7419 [get_ports mcio_vio_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.6922 [get_ports mcio_vio_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.8000 [get_ports mcio_vio_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7699 [get_ports mcio_vio_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.85 [get_ports mcio_vio_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.8150 [get_ports mcio_vio_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.9261 [get_ports mcio_vio_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.9102 [get_ports mcio_vio_oe[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7417 [get_ports mcio_vio_out[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.6976 [get_ports mcio_vio_out[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.8112 [get_ports mcio_vio_out[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7835 [get_ports mcio_vio_out[0]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7538 [get_ports mcio_vio_out[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.7106 [get_ports mcio_vio_out[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.8225 [get_ports mcio_vio_out[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7948 [get_ports mcio_vio_out[1]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7652 [get_ports mcio_vio_out[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.7164 [get_ports mcio_vio_out[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.8327 [get_ports mcio_vio_out[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7997 [get_ports mcio_vio_out[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7389 [get_ports mcio_vio_out[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.700 [get_ports mcio_vio_out[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.8125 [get_ports mcio_vio_out[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7897 [get_ports mcio_vio_out[3]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7549 [get_ports test[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.7204 [get_ports test[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.8093 [get_ports test[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7905 [get_ports test[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -max -add_delay -0.7385 [get_ports test_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -max -add_delay -0.6876 [get_ports test_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -rise -min -add_delay -0.8 [get_ports test_oe[2]]
set_output_delay -clock v_acx_sc_GPIO_H_IOB1_GLB_SER_GEN_CLK -fall -min -add_delay -0.7741 [get_ports test_oe[2]]
# Boundary pin delays for vp_gpio_s_b2
# Core Data
# Boundary pin delays for vp_pll_nw_2
# Boundary pin delays for vp_pll_sw_2

######################################
# End IO Ring Boundary Delays SDC File
######################################
